### ISSUE TITLE
Allow attributes beginning with '*' 

### ISSUE THREAD

**Issue by kantianethics** [scala/scala-xml#111]
`scala> val x = <div ngIf="selectedHero"></div>`
compiles, but
`scala> val x = <div *ngIf="selectedHero"></div>`
throws
```
<console>:1: error: in XML literal: '>' expected instead of '*'
val x = <div *ngIf="selectedHero"></div>
             ^
```

Angular 2 recommends preceding built-in directives with '*'.

**Comment by biswanaths** [comment]
I don't think asterisk is a valid character to start with attribute name in xml. Please do correct me if I am wrong. https://www.w3.org/TR/REC-xml/#NT-Name

Also I think you must have figured this out, you can rewrite the xml element as

`val x = <div template="ngIf selectedHero"></div>`

**Comment by biswanaths** [comment]
Also, little curious, why you are generating the Angular fragments from xml ?

**Comment by kantianethics** [comment]
My bad, should've checked the spec. It's pretty annoying that the built-in directives actually break the spec. 

I needed to do some html processing on the server. Like you mentioned, I'll just use the more wordy `template` alternative.

Thanks for the fast response.
