### ISSUE TITLE
Non exhaustive match warning while testing.

### ISSUE THREAD

**Issue by biswanaths** [scala/scala-xml#114]
The following waring is generated while testing. 

```
[warn] /home/b1swanath/code/scala-xml/src/test/scala/scala/xml/ReuseNodesTest.scala:86: match may not be exhaustive.
[warn] It would fail on the following inputs: (List(_), Nil), (Nil, List(_))
[warn]     (original.toList,transformed.toList) match {
[warn]     ^
[warn] one warning found

```
How to reproduce, 

do "sbt clean" followed by "sbt test".

**Comment by ashawley** [comment]
I think I ran across this as well.  It might be #83, but it's been a while for me to remember if that's the same warning or not.

**Comment by biswanaths** [comment]
@ashawley : You are right. Your PR #83 is taking care of this.

**Comment by biswanaths** [comment]
#83 Will take care of this. Thanks agian @ashawley .
