### ISSUE TITLE
NodeBuffer does print as ArrayBuffer

### ISSUE THREAD

**Issue by jschmuec** [scala/scala-xml#115]
`new scala.xml.NodeBuffer() &+ scala.xml.Text("Text 1")`

should print as:

`NodeBuffer(Text 1)`

but prints as 

`ArrayBuffer(Text 1)`.

I think you just need to add

`override def stringPrefix: String = "NodeBuffer"`

**Comment by biswanaths** [comment]
@jschmuec : Thank you for reporting this.

**Comment by ashawley** [comment]
This was fixed in #117.  Thanks for reporting this.  With any luck, this will be released in 1.0.7 relatively soon.
