### ISSUE TITLE
ArrayBuffer.result() returns ArrayBuffer but should return Array

### ISSUE THREAD

**Issue by jschmuec** [scala/scala-xml#116]
The result method should convert the ArrayBuffer to an immutable version. So it should return scala.collection.Array and not scala.collection.mutable.ArrayBuffer as it does.

Replace

`def result : ArrayBuffer[A] = this `

with

`def result : Array[A] = this`

**Comment by biswanaths** [comment]
Thank you  @jschmuec for reporting this. 

Also would you be kind enough to add more information about this ? I am not able to locate the code snippet you have mentioned in the issue.

**Comment by SethTisue** [comment]
Yeah, this is about Scala. @jschmuec if there's a bug in the Scala collections you'd open an issue on https://issues.scala-lang.org, but if it's your first bug report, I'd suggest that you start on Gitter or on the scala-user mailing list and talk to the community first about whether it's really a bug or not, before opening an issue in the bug tracker.

**Comment by jschmuec** [comment]
Sorry for nit sticking to protocol. Sounds like a waste for something that I thought is just a trivial glitch. I looked at the ArrayBuffer a bit more and see that it doesn't implement the behaviour that I wouepldvhave expected at all. Will raise that for discussion as it's a big bug.

Which also brings me to the question if it wouldn't be good to implement mutations on List similar to how Clojure does it. I know that I can do that anyhow for my own code.
