### ISSUE TITLE
let's delete the scala-xml google group

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-xml#130]
I suggest we officially retire it, there's been no traffic there for a long time. the repo readme here doesn't even link to it, nor does http://www.scala-lang.org/community/

any objections?

https://groups.google.com/forum/#!forum/scala-xml

**Comment by SethTisue** [comment]
There don't seem to be any objections.

I looked at the group archives quickly, and it looks like very few legitimate messages were ever sent there, so I'm thinking it would be fine to simply delete the group outright.

Is there someone who 1) thinks the group archives are worth preserving and 2) volunteers to somehow preserve them elsewhere so we can delete the group?

I suggest we delete the group on March 1, regardless of whether a volunteer for this has stepped forward.

**Comment by fsalvi** [comment]
Yes, I have owner access on this group, so I can delete it.
I had a look, but unfortunately, there is no export function in google groups...

**Comment by fsalvi** [comment]
There's this contrib code if someone wants to try:
http://saturnboy.com/2010/03/scraping-google-groups/

**Comment by SethTisue** [comment]
@fsalvi can you go ahead and delete the group now, please?

**Comment by fsalvi** [comment]
Ok, done.

**Comment by SethTisue** [comment]
thank you, Fabien!
