### ISSUE TITLE
scavenge anything from to-be-retired XML section of Scala tour?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-xml#138]
is there anything here that should be rescued and added to this repo instead?

https://github.com/scala/scala.github.com/pull/743

**Comment by ashawley** [comment]
Thanks for the heads up on this.  

That PR is deceptive. It looks like a new post, dated 2017-02-13, but apparently things are getting re-arranged for some reason.

The piece is from 2011 and written by Josh Suereth in scala/scala.github.com@897691d

**Comment by ashawley** [comment]
I've dumped them in the Wiki for now.

https://github.com/scala/scala-xml/wiki/XML-Processing

I did the translations as well, for what that's worth.
