### ISSUE TITLE
add Scala 2.13.0-Mx to `crossScalaVersions`

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-xml#142]
for x=1, currently

because of the circular dependency between scalac and scala-xml, the Scala release process also publishes scala-xml, so 1.0.6 is already published for 2.13.0-M1

so, this isn't pressing.

nonetheless, it would be good to have 2.13.0-M1 in crossScalaVersions, so that if a new scala-xml version is released, it gets published for that Scala version

**Comment by ashawley** [comment]
Ok, then we'll need definitely need to bump a la #141 to support a 2.13. Otherwise, mima will fail when building because it won't have a previous 2.13 build (unless somebody publishes a 1.0.5 build with 2.13).   In this case, the circular dependency helps rather than hurts in this way.

**Comment by SethTisue** [comment]
Oh haha you already thought through what I just got done writing on the other ticket.

**Comment by ashawley** [comment]
Hilarious!  Well, hopefully we came around to the same conclusions.

**Comment by ashawley** [comment]
Looks like @lrytz is working on this in #145

**Comment by ashawley** [comment]
The  sbt-scala-modules plugin uses `scalaVersionsByJvm` to set `crossScalaVersions in the build, and it's done so for 2.13.0-M1
