### ISSUE TITLE
Publish 1.0.7

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#152]
I'd like to propose releasing what we have so far as version 1.0.7  I predict this may take some coordination since it will be the first time publishing artifacts for Scala.js.  Is there any preparation that needs to be done to support Scala.js?

I'll be adding a draft of the release notes as a comment to this ticket, shortly.

**Comment by SethTisue** [comment]
> Is there any preparation that needs to be done to support Scala.js?

only thing I can think of is to not repeat https://github.com/scala/scala-parser-combinators/issues/119

**Comment by ashawley** [comment]
Looks like the tldr is to not repeat publishing empty sjs jars.

**Comment by ashawley** [comment]
- Add Scala.js support with [#109](/scala/scala-xml/pull/109), [#131](/scala/scala-xml/pull/131), [#133](/scala/scala-xml/pull/133)
- Fix [#121](/scala/scala-xml/issues/121), changes default encoding in `XML.save` to UTF-8 in [#122](/scala/scala-xml/pull/122)
- Fix [#46](/scala/scala-xml/issue/46) with new config for minimizing tags in `PrettyPrinter`, see [#90](/scala/scala-xml/pull/90)
- Fix defect [#72](/scala/scala-xml/issues/72) `XMLEventReader` does not handle `&apos;` properly with [#89](/scala/scala-xml/pull/89)
- Fix defect [#44](/scala/scala-xml/pull/44) with fifth-edition names [SI-9060](/scala/bug/issues/9060) in [#93](/scala/scala-xml/pull/93)
- Fix defect [#115](/scala/scala-xml/issues/115) `NodeBuffer.toString` with [#117](/scala/scala-xml/pull/117)
- Fix defect [#118](/scala/scala-xml/issues/118) Scaladoc links in apidocs to Scala standard library with [#119](/scala/scala-xml/pull/119)
- Fix performance issue [#136](/scala/scala-xml/pull/136) lock contention from `lazy val` in `MetaData.normalize`
- Revert `Utility.escape` implementation to use `Iterator` instead of `while` with [#102](/scala/scala-xml/pull/102)
- Convert deprecated use of `mutable.Stack` to `List` in [#150](/scala/scala-xml/pull/150)
  - Changes the following members in the abstract class `scala.xml.parsing.FactoryAdapter`
    - `attribStack`
    - `hStack`
    - `tagStack`
    - `scopeStack`
  - This abstract class is used within the library, as well, by the following:
    - `scala.xml.parsing.NoBindingFactoryAdapter` implemented class
    - `scala.xml.factory.XMLLoader.adapter` static member

**Comment by SethTisue** [comment]
(I'd suggest publicizing this ticket a bit on contributors.scala-lang.org)

**Comment by ashawley** [comment]
Ok, I'll work on writing a post

**Comment by ashawley** [comment]
https://contributors.scala-lang.org/t/upcoming-scala-xml-1-0-7/985

**Comment by ashawley** [comment]
It was found that #150 was a breaking change for the lift framework and probably others, so we'll need to release as 1.1.0 and improve the release notes about the breaking change.
