### ISSUE TITLE
is there some general "how to use embedded XML in Scala" page the readme could link to?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-xml#162]
we link to the API doc, but that's jumping ahead, is there a total-beginner thing that shows how to write XML literals, pattern match, etc.?

**Comment by SethTisue** [comment]
there's http://www.scala-lang.org/old/node/131, but perhaps there's something better/newer?

**Comment by ocramz** [comment]
I'm having this exact same issue right now. The idioms for manipulating XML have been seemingly changes in recent years and the resources online don't give a coherent picture.

**Comment by SethTisue** [comment]
some intro text could be rescued from https://github.com/scala/docs.scala-lang/pull/743/files

**Comment by ashawley** [comment]
I moved those notes to the GitHub wiki, but they haven't received much google juice, yet.  See:

https://github.com/scala/scala-xml/wiki

**Comment by SethTisue** [comment]
ah... so maybe the solution to this would be to just add a wiki link to the readme?

**Comment by ashawley** [comment]
Yes, adding to the README would be good, as would generally filling out and improving the wiki.  I've been meaning to do it, but people can jump ahead of me.

**Comment by ashawley** [comment]
I've filled out the Wiki a bit and added a link to it in the README

https://github.com/scala/scala-xml/wiki
