### ISSUE TITLE
Broken Link on main page

### ISSUE THREAD

**Issue by wongjoel** [scala/scala-xml#170]
There is a broken link at the top of the main page (main page being https://github.com/scala/scala-xml)

```
The standard Scala XML library. http://docs.scala-lang.org/scala
```

Unfortunately, http://docs.scala-lang.org/scala now results in a 404 error. Not sure if the link is pointing to the wrong place, or if the site is currently not serving the page for that link.

Thanks for your time.

**Comment by ashawley** [comment]
Thanks for reporting this.  Not sure what that link was going to before.  I've removed it for now, since we now have the GitHub wiki, and the API links are "below the fold" in the README
