### ISSUE TITLE
Add JDK 9 to Travis

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#173]
Running in Java 9 should be possible.  It may require an update to sbt?

Trying it in Travis, I get the following:

    error: error while loading package, Missing dependency 'object java.lang.Object in compiler mirror',
    required by /home/travis/.sbt/boot/scala-2.10.6/lib/scala-library.jar(scala/package.class)
    error: error while loading package, Missing dependency 'object java.lang.Object in compiler mirror'
    required by /home/travis/.sbt/boot/scala-2.10.6/lib/scala-library.jar(scala/runtime/package.class)
    scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.

**Comment by ashawley** [comment]
Or maybe an update to sbt-scala-module plugin, see scala/sbt-scala-module#35

**Comment by SethTisue** [comment]
Let's come back to this once Scala 2.10.7 and sbt 0.13.17 come out.

(In the context of https://github.com/scala/community-builds/issues/609 I do have scala-xml building on Java 9; that's good enough for now, messing around with the same workarounds in the Travis config here isn't necessary.)

**Comment by ashawley** [comment]
Looks like Scala 2.11.12 and 2.12.4 fixed it, or do we need really need a new sbt?

**Comment by ashawley** [comment]
I was wrong, we really are waiting on a new sbt.

**Comment by SethTisue** [comment]
now that Scala 2.10.7 is on Maven Central, we don't actually need a new sbt because we can just `sbt -Dsbt.scala.version=2.10.7` (as a workaround until 0.13.17 comes out with that as the default)

but it doesn't matter right now because scala/sbt-scala-module#35 is still a blocker, I think
