### ISSUE TITLE
Can't use new 1.1.0 version

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#195]
Tis the season when people can't use the new scala-xml version, because they need to:

```
fork := true
```

This should be documented more prominently.

This is because the scala-xml used by scaladoc in the compiler is being picked up first in sbt-land.

**Comment by SethTisue** [comment]
is there some `dependencyOverrides` type of thing we can recommend...?

**Comment by ashawley** [comment]
I dunno. Are the compiler dependencies mungable in sbt?  Or are they too early in the classpath to reach?  Something like that would be a nice alternative for people to just the JVM forking solution.

**Comment by SethTisue** [comment]
@dwijnand can you think of a way to force this...?

**Comment by SethTisue** [comment]
@ashawley does this help? https://github.com/scala/scala-dev/issues/291

**Comment by SethTisue** [comment]
a sampling of other tickets in this area:

* https://github.com/scala/scala-module-dependency-sample/pull/14
* https://github.com/scala/bug/issues/9560

**Comment by eed3si9n** [comment]
Repro step is that you can `run` from sbt using scala-xml version other than the one scala compiler is using correct? If so, this is an sbt bug.

**Comment by ashawley** [comment]
> Repro step is that you can run from sbt using scala-xml version other than the one scala compiler is using correct?

I believe Joe Barnes showed, in the sbt bug report that Seth cited, the defect was broken for both `run` and `test`, and presumably everywhere, unless JVM forking was used.

**Comment by ashawley** [comment]
Looks like the other sbt hack is to add the following to your `project/build.properties`:

```
sbt.version=1.1.2
```

Much respect to Eugene for getting this fixed.  Thank you!

**Comment by SethTisue** [comment]
shall we close this, then?

**Comment by eed3si9n** [comment]
I think we should close it since the bug is in sbt (sbt/sbt#3405) not scala-xml itself.

**Comment by ashawley** [comment]
It was mostly a confusion and documentation issue.  

I've updated the wiki:

https://github.com/scala/scala-xml/wiki/Getting-started
