### ISSUE TITLE
publish for 2.13.0-M4

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-xml#217]
M4 isn't quite out yet, but opening the ticket while I think of it

now that scala-xml is out of the Scala bootstrap, that means it is no longer automatically published whenever we publish Scala. so @ashawley you'll need to pull the publishing levers

**Comment by SethTisue** [comment]
M4 JARs are on Maven Central

**Comment by SethTisue** [comment]
Sébastien thinks Scala.js will likely publish tomorrow. Lukas says let's not publish JVM-only in the meantime, let's just wait. Fine w/ me

**Comment by ashawley** [comment]
Ok, I'll wait for this to be resolved:

```
> update
[error] (xmlJS/*:update) sbt.ResolveException: unresolved dependency: org.scala-js#scalajs-library_2.13.0-M4;0.6.22: not found
[error] unresolved dependency: org.scala-js#scalajs-test-interface_2.13.0-M4;0.6.22: not found
[error] unresolved dependency: org.scala-js#scalajs-junit-test-runtime_2.13.0-M4;0.6.22: not found
[error] unresolved dependency: org.scala-js#scalajs-compiler_2.13.0-M4;0.6.22: not found
[error] unresolved dependency: org.scala-js#scalajs-junit-test-plugin_2.13.0-M4;0.6.22: not found
```

**Comment by ashawley** [comment]
I've updated Lukas's [newCollectionsBoostrap](https://github.com/scala/scala-xml/compare/newCollectionsBootstrap) branch with

1. the 2.13.0-M4 version and 
2. the scala-js update and
3. rebased with the latest master.

To make a release, I need to rebase onto the 1.1.0 tag.

```
$ git checkout newCollectionsBootstrap
$ git rebase --onto v1.1.0 e02c2be^ publish-1.1.0_2.13.0-M4
```

I'm using the commit before e02c2be as the diverge point, since it is the merge for #210 which contained some small 2.13 collections changes that need to also be included.

**Comment by ashawley** [comment]
I pushed the tag [v1.1.0-scala-2.13.0-M4](https://github.com/scala/scala-xml/releases/tag/v1.1.0-scala-2.13.0-M4).

Looking at the Travis build output, it doesn't look like it got published to sonatype for some reason.

😕

**Comment by lrytz** [comment]
I think it should work with the tag named `v1.1.0#2.13.0-M4#8`. Testing this here: https://github.com/scala/scala-xml/releases/tag/v1.1.0%232.13.0-M4%238.

**Comment by lrytz** [comment]
Travis build: https://travis-ci.org/scala/scala-xml/builds/380701707. Staging repo: https://oss.sonatype.org/content/repositories/orgscala-lang-1571

Can you double check if it looks good to you?

**Comment by ashawley** [comment]
Looks good to me!

Thanks for fixing my release tag!

**Comment by SethTisue** [comment]
I hit "Release" on the staging repository

**Comment by SethTisue** [comment]
JARs are on Maven Central.

```
% mkdir xml-test
% cd xml-test
% sbt
[warn] No sbt.version set in project/build.properties, base directory: /Users/tisue/tmp/xml-test
[info] Set current project to xml-test (in build file:/Users/tisue/tmp/xml-test/)
[info] sbt server started at local:///Users/tisue/.sbt/1.0/server/65a7bac1e225d59b418a/sock
sbt:xml-test> ++2.13.0-M4!
[info] Forcing Scala version to 2.13.0-M4 on all projects.
[info] Reapplying settings...
[info] Set current project to xml-test (in build file:/Users/tisue/tmp/xml-test/)
sbt:xml-test> console
[info] Updating ...
[info] Done updating.
[info] Starting scala interpreter...
Welcome to Scala 2.13.0-M4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> <foo/>
       ^
       error: To compile XML syntax, the scala.xml package must be on the classpath.
       Please see https://github.com/scala/scala-xml for details.

scala> 
[success] Total time: 6 s, completed May 18, 2018 7:39:18 PM
sbt:xml-test> set libraryDependencies += "org.scala-lang.modules" %% "scala-xml" % "1.1.0"
[info] Defining libraryDependencies
[info] The new value will be used by allDependencies, dependencyPositions
[info] Reapplying settings...
[info] Set current project to xml-test (in build file:/Users/tisue/tmp/xml-test/)
sbt:xml-test> console
[info] Updating ...
[info] Done updating.
[info] Starting scala interpreter...
Welcome to Scala 2.13.0-M4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> <foo/>
res0: scala.xml.Elem = <foo/>
```
