### ISSUE TITLE
locally-built classes should not break ivy resolution in scala-tool config

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-xml#22]
when resolving scala-compiler for, say, the doc task, no scala-xml jar is put on the classpath when the compiler's scala-xml dependency has the same version as the one we're building now.

This can be patched by appending the locally built jar to ScalaInstance's classpath. Ideally, we'd keep this project out of the resolution process entirely so we end up with the correct scala-xml dependency for scala-compiler.

This only really comes up during bootstrapping, where we work around it by setting the local version to a dummy, run the doc task, then reset the version: https://github.com/scala/jenkins-scripts/blob/master/job/scala-release-2.11.x#L114

I tried to implement that but failed (failed attempt below).

```
// to avoid problem with circular dependency when bootstrapping the modules
compilers in (Compile, doc) := {
  val instance = scalaInstance.value
  val cp = (packageBin in Compile).value +: instance.allJars
  println(s"Classpath for scalaInstance =\n\t * ${cp mkString "\n\t * "}")
  val launcher = appConfiguration.value.provider.scalaProvider.launcher
  val newInstance = ScalaInstance(instance.libraryJar, instance.compilerJar, launcher, cp:_*)
  Compiler.compilers(newInstance, classpathOptions.value, javaHome.value)(appConfiguration.value, streams.value.log)
}
```

This doesn't work (even with the crazy hacks to force an update)

```
val scalaInstanceFromUpdate = TaskKey[ScalaInstance]("scala-instance-from-update", "Defines the Scala instance to use for compilation, running, and testing.")

scalaInstanceFromUpdate := Defaults.scalaInstanceFromUpdate.value

scalaInstance := {
 val s = state.value
 val extracted = Project.extract(s)
 val newState = extracted.append(List(version := "1.0.0-BLA", libraryDependencies += "junit" % "junit" % "4.10" % "scala-tool"), s)
 val newState2 = extracted.runTask(Keys.update, newState)._1
 val inst = extracted.runTask(scalaInstanceFromUpdate, newState2)._2
 println(inst.allJars.toList)
 inst
}
```

**Comment by SethTisue** [comment]
it seems highly unlikely this will be addressed except by just removing scala-xml from the 2.13 bootstrap entirely
