### ISSUE TITLE
Relicense under Apache 2.0

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#227]
https://contributors.scala-lang.org/t/moving-to-the-apache-v2-0-license/1859

**Comment by SethTisue** [comment]
@adriaanm legally, can we do this?

**Comment by adriaanm** [comment]
Yes, assuming signed CLAs for all contributors since modularization

**Comment by ashawley** [comment]
It seems like nearly all contributors since modularization (1 Jan 2013?) are also contributors to Scala, and therefore are recent and familiar faces that likely have a CLA on file.  It wouldn't be hard to find the few exceptions to that group, and work on tracking them down and signing the CLA.

**Comment by ashawley** [comment]
I mined the git history, and I've contacted a dozen contributors who I presumed didn't have a CLA on file.  I've heard back from about half of them, so far.  I'll report back whether I hear back from the rest.

Here's the form letter I'm sending.

> Dear <person's name>
>
> I am one of the maintainers of scala-xml.  I want to thank you for your contribution to scala-xml a while back.  There is a new proposal to relicense much of Scala under the Apache License.  As part of that initiative, I am contacting contributors of scala-xml.   Would you let me know if you have signed the Lightbend CLA or, if not, whether you would be able to?
>
> https://www.lightbend.com/contribute/cla/scala
> 
> From the page above, click on the link "Sign the agreement using your github account", which is this URL:
> 
> https://www.lightbend.com/contribute/cla/scala/sign
> 
> You'll be asked to sign-in with your GitHub account, and then submit your confirmation to Lightbend.
> 
> For more information on the initiative of moving from the "modified" BSD license to Apache 2.0 license, see the following post on the Scala contributor forum (Discourse):
> 
> https://contributors.scala-lang.org/t/moving-to-the-apache-v2-0-license/1859
> 
> Thanks,
> Aaron

**Comment by SethTisue** [comment]
https://github.com/scala/scala-xml/wiki/Contributor-guide mentions the old license
