### ISSUE TITLE
oraclejdk10 not working in Travis-CI build matrix

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-xml#244]
seen at e.g. https://travis-ci.org/scala/scala-xml/builds/405055869 — I hit "restart" on the failed builds but it didn't help, so apparently there is something real here

**Comment by ashawley** [comment]
Seems to be a Travis issue:

```
The command "bash install-jdk.sh -F 10 -L BCL --target $JAVA_HOME
 --workspace $HOME/.cache/install-jdk" failed and exited with 8 during .
```

Not very insightful.  It "exited with 8 during [...]."

Reminds me of a scene from a Monty Python movie: "It reads, 'Here may be found the last words of Joseph of Arimathea. He who is valiant and pure of spirit may find the Holy Grail in the [Castle of aaarrrrggh](http://montypython.50webs.com/scripts/Holy_Grail/Scene21.htm)'."

**Comment by ashawley** [comment]
Builds in oraclejdk10 are getting further, now.   Looks like Travis was able to resolve this in https://github.com/travis-ci/travis-ci/issues/9895
