### ISSUE TITLE
Serialization in 2.13.0-M5

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#254]
I tried compiling on the latest M5 with [Seth's branch](https://github.com/scalacommunitybuild/scala-xml/tree/community-build-2.13) and get serialization issues:

```
[error] Test scala.xml.SerializationTest.unmatched failed: expected:<> but was:<List()>, took 0.078 sec
[error] Test scala.xml.SerializationTest.xmlLiteral failed: expected:<<node/>> but was:<List(scala.collection.generic.DefaultSerializationProxy@28ec9fc9)>, took 0.013 sec
[error] Test scala.xml.SerializationTest.implicitConversion failed: expected:<<child></child><child/>> but was:<List(List(scala.collection.generic.DefaultSerializationProxy@5844dad8), List(scala.collection.generic.DefaultSerializationProxy@3204a005))>, took 0.002 sec
[error] Test scala.xml.SerializationTest.empty failed: expected:<> but was:<List()>, took 0.001 sec
[error] Test scala.xml.XMLTestJVM.serializeAttribute failed: java.lang.ClassCastException: scala.collection.immutable.$colon$colon cannot be cast to scala.xml.Attribute, took 0.011 sec
[error]     at scala.xml.XMLTestJVM.serializeAttribute(XMLTest.scala:218)
[error]     ...
[error] Test scala.xml.XMLTestJVM.serializeDocument failed: java.lang.ClassCastException: scala.collection.immutable.$colon$colon cannot be cast to scala.xml.Document, took 0.016 sec
[error]     at scala.xml.XMLTestJVM.serializeDocument(XMLTest.scala:228)
[error]     ...
[error] Test scala.xml.XMLTestJVM.serializeElem failed: java.lang.ClassCastException: scala.collection.immutable.$colon$colon cannot be cast to scala.xml.Elem, took 0.002 sec
[error]     at scala.xml.XMLTestJVM.serializeElem(XMLTest.scala:236)
[error]     ...
[error] Test scala.xml.XMLTestJVM.serializeComplex failed: java.lang.ClassCastException: scala.collection.immutable.$colon$colon cannot be cast to scala.xml.Elem, took 0.082 sec
[error]     at scala.xml.XMLTestJVM.serializeComplex(XMLTest.scala:271)
[error]     ...
[error] Failed: Total 164, Failed 8, Errors 0, Passed 156
[error] Failed tests:
[error] 	scala.xml.XMLTestJVM
[error] 	scala.xml.SerializationTest
```

When I look in the last passing [2.13 community build from Aug-22](https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/1375/) I only see scala-xml getting skipped:

```
[scala-xml] --== Building scala-xml ==--
[scala-xml] Found cached project build, uuid 4cab6219ea2340373d5bbf922cd70ba828d91bfd
[scala-xml] --== End Building scala-xml ==--
```

According to @xuwei-k in [comment in scala-xml#253](https://github.com/scala/scala-xml/issues/253#issuecomment-417146558), the issue is related to changes

> Should we change `scala.Iterable#writeReplace` implementation from the viewpoint of compatibility and liskov substitution principle? 🤔 
> https://github.com/scala/scala/pull/6676
> - https://github.com/xuwei-k/scala-xml/commit/97bc6b4e9e09b91937528ddf5a2d131cbac278ec
> - https://github.com/scala/scala/blob/v2.13.0-M5/src/library/scala/collection/Iterable.scala#L42-L46

I'm not sure how @xuwei-k found this so quickly, but indeed xuwei-k/scala-xml@97bc6b4 fixed my issue.

```patch
commit 97bc6b4e9e09b91937528ddf5a2d131cbac278ec (xuwei-k/writeReplace)
Author: xuwei-k
Date:   Thu Aug 30 09:09:04 2018 +0900

    override writeReplace. fix serialize error

diff --git a/shared/src/main/scala/scala/xml/MetaData.scala b/shared/src/main/scala/scala/xml/MetaData.scala
index 1affff4e..cdb98851 100644
--- a/shared/src/main/scala/scala/xml/MetaData.scala
+++ b/shared/src/main/scala/scala/xml/MetaData.scala
@@ -225,4 +225,6 @@ abstract class MetaData
 
   final def remove(namespace: String, owner: Node, key: String): MetaData =
     remove(namespace, owner.scope, key)
+
+  protected[this] override def writeReplace(): AnyRef = this
 }
diff --git a/shared/src/main/scala/scala/xml/NodeSeq.scala b/shared/src/main/scala/scala/xml/NodeSeq.scala
index 97b2ddf2..c99fe978 100644
--- a/shared/src/main/scala/scala/xml/NodeSeq.scala
+++ b/shared/src/main/scala/scala/xml/NodeSeq.scala
@@ -155,4 +155,6 @@ abstract class NodeSeq extends AbstractSeq[Node] with immutable.Seq[Node] with S
   override def toString(): String = theSeq.mkString
 
   def text: String = (this map (_.text)).mkString
+
+  protected[this] override def writeReplace(): AnyRef = this
 }
```

**Comment by ashawley** [comment]
I don't know enough about the broad consequences to promote this to a Scala bug and have a minimal example, although it seems it should.

As is, we would need to have a mix-in trait that would provide `writeReplace` to fix this in 2.13, and then a no-op version for 2.12 and earlier.

I'm surprised this wasn't caught earlier in the community build.  If the issue is scala/scala#6676 as @xuwei-k states, then it would have been an issue since it was merged on May-25.  Maybe there was an issue with scala-xml in the community build that was giving a false positive and contributing to a false sense of security?

I'm not surprised that it didn't get caught in the compiler test suite since scala-xml and a few tests were removed in M5  https://github.com/scala/scala/pull/6436 on Apr-25.  Some partests for XML literals were added back in https://github.com/scala/scala/pull/6569 on Apr-27, but they wouldn't have caught this serialization issue.

**Comment by xuwei-k** [comment]
excluded some tests in community-builds 😢 
https://github.com/scala/community-builds/commit/87e67eac29a48727b123158ffc2cb1c229f7a3f0#diff-13924878884a607db34ef8aa8c07a253R200

**Comment by lrytz** [comment]
cc @szeiger

**Comment by SethTisue** [comment]
umbrella ticket for serialization issue(s) in 2.13: https://github.com/scala/scala-dev/issues/562

**Comment by ashawley** [comment]
I was able to fix the serialization issue in 2.13.0-M5 with a trait overriding `writeReplace`, but I was unable to keep the 2.11 and 2.12 builds working with a null trait:

```
> xml/testOnly scala.xml.PatternMatching
[error] Test scala.xml.PatternMatching.nodeSeq failed: expected:<<a/><b/>> but was:<List(<a/>, <b/>)>, took 0.047 sec
[error] Failed: Total 6, Failed 1, Errors 0, Passed 5
```

I think Kenji Yoshida was hinting as much?:

> Should we change `scala.Iterable#writeReplace` implementation from the viewpoint of compatibility and liskov substitution principle? 🤔

**Comment by ashawley** [comment]
I just closed the 2.13 WIP pull request that included the strange workaround for this Scala 2.13 bug, but it would be great to take it out in the future.

**Comment by SethTisue** [comment]
https://github.com/scala/scala/pull/7624 cements the new serialization scheme, so this isn't going to be "fixed" any further on the Scala end.

the typical workarounds are to either:

* set `fork in Test := true`
* use a custom classloader that works around the JVM flaw which is the root cause

sbt 1.3 will use a flatter classloader structure that we believe will make the `fork` around unnecessary

**Comment by ashawley** [comment]
The specific serialization issue was fixed, so we can close.  I should  have done that after merging #276.
