### ISSUE TITLE
Release 1.1.1

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#255]
Want to get this out, and then move on to mainlining Scala 2.13 changes and prepare for 1.2.x.

Draft release notes:

This is a patch release of Scala XML that is binary and source compatible with the previous release, 1.1.0.

- Fix #73, `Utility.trim` should handle whitespace between adjacent `Text()` nodes
- Fix #160, support nested escaped CDATA sections
- Fix #192, deprecate XMLEventReader, and suggest `javax.xml.stream.events.XMLEvent`
- Fix #32 and #209, out-of-memory error with `ConstructingParser`
- Fix #231, avoid splitting up empty elements with `PrettyPrinter(minimizeEmpty = true)`
- Fix #251, make invalid argument exception the same type for `NodeSeq.\\()`
- Doc fixes and improvements for #178, #214, and #232
- Change license to Apache 2.0, #227

**Comment by ashawley** [comment]
I'm blocked with https://github.com/scala/sbt-scala-module/issues/41

**Comment by ashawley** [comment]
Doesn't seem like there's a way to publish a 2.11 version on Java 6 and I don't want to entertain publishing jars with Java 7 or 8.  It would seem a recipe for disaster.  We'll just drop support for 2.11 release here, and re-visit later if it becomes necessary.

**Comment by ashawley** [comment]
Unexpectedly, the 2.11 builds were published:

```
$ java -Xmx32m -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
$ javac -J-Xmx32m -version
javac 1.8.0_151
Using Scala 2.11.12
[...]
$ if [[ $JAVA_HOME = *java-6* ]]; then jdk_switcher use openjdk6; fi
Switching to OpenJDK6 (java-1.6.0-openjdk-amd64), JAVA_HOME will be set to /usr/lib/jvm/java-6-openjdk-amd64
update-java-alternatives: plugin alternative does not exist: /usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/IcedTeaPlugin.so
The command "if [[ $JAVA_HOME = *java-6* ]]; then jdk_switcher use openjdk6; fi" exited with 0.
0.07s$ java -version
java version "1.6.0_41"
OpenJDK Runtime Environment (IcedTea6 1.13.13) (6b41-1.13.13-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 23.41-b41, mixed mode)
[...]
$ admin/build.sh
Releasing 1.1.1 with Scala 2.11.12 on Java version 6.
Detected sbt version 0.13.17
[...]
[info] 	published scala-xml_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scala-lang/modules/scala-xml_2.11/1.1.1/scala-xml_2.11-1.1.1-javadoc.jar.asc
[info] 	published scala-xml_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scala-lang/modules/scala-xml_2.11/1.1.1/scala-xml_2.11-1.1.1.jar.asc
[info] 	published scala-xml_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scala-lang/modules/scala-xml_2.11/1.1.1/scala-xml_2.11-1.1.1.pom
[info] 	published scala-xml_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scala-lang/modules/scala-xml_2.11/1.1.1/scala-xml_2.11-1.1.1-sources.jar
[info] 	published scala-xml_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scala-lang/modules/scala-xml_2.11/1.1.1/scala-xml_2.11-1.1.1-javadoc.jar
[info] 	published scala-xml_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scala-lang/modules/scala-xml_2.11/1.1.1/scala-xml_2.11-1.1.1-sources.jar.asc
[info] 	published scala-xml_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scala-lang/modules/scala-xml_2.11/1.1.1/scala-xml_2.11-1.1.1.jar
[info] 	published scala-xml_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scala-lang/modules/scala-xml_2.11/1.1.1/scala-xml_2.11-1.1.1.pom.asc
[success] Total time: 11 s, completed Sep 26, 2018 5:32:39 PM
```

**Comment by adriaanm** [comment]
@ashawley is it ok if I promote the staging repos? It looks like sonatype decided to mix-and-match the staging of scala-xml 1.1.1 and scala 2.12.7, meaning they will have to be promoted to maven central at the same time. We're good to go on our end -- let me know when I can :shipit:  :-)

**Comment by ashawley** [comment]
@adriaanm Yes, you can publish 1.1.1 artifacts for scala-xml.  Thanks!

**Comment by SethTisue** [comment]
yay! @ashawley would you like to tweet about it, and then I'll retweet from scala_lang?

**Comment by ashawley** [comment]
Yes, will do.  I'll wait for the Scala 2.12.7 fanfare to die down, and also get a 2.13.0-M5 build for 1.1.1 out, as well.

**Comment by SethTisue** [comment]
@ashawley hoopla died down enough?

**Comment by SethTisue** [comment]
retweeted
