### ISSUE TITLE
publish for Scala 2.13.0-M5

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-xml#256]

**Comment by SethTisue** [comment]
probably blocked for now by https://github.com/scala-js/scala-js/issues/3443 ?

**Comment by SethTisue** [comment]
"Scala.js 0.6.25 is now released with support for Scala 2.13.0-M5"

@ashawley is anything blocking us here? do you expect to get to this soon, like in the next couple days, say... or would you like the Scala team to handle it this time...? either way's fine

**Comment by SethTisue** [comment]
if the answer is "we're blocked by https://github.com/scala/sbt-scala-module/issues/41", gah, what a mess, it seems there are multiple possible ways forward there and I've gotten lost in all the options

in this repo, at https://github.com/scala/scala-xml/issues/217, for M4 it looks like we didn't need to completely sort this out, instead we can just push a tag like `v1.1.0#2.13.0-M5#8` (after including any M5 changes) and it should work, it worked last time. yes? or am I missing something?

**Comment by ashawley** [comment]
I updated my collectionsBootstrap branch, and got it to compile on M5.  I was just waiting on Scala.js, but it sounds like that's ready now.  I'll try to work on getting it publishing in the next few days.

Indeed, we were able to publish 2.13.0-M4 as you describe.  The Java 6 failures won't keep us from publishing 2.13.0-M5.

**Comment by ashawley** [comment]
I pushed a new tag `v1.1.0#2.13.0-M5#8` and it looks like it published to sonatype.

I've updated the [newCollectionBootstrap](https://github.com/scala/scala-xml/compare/newCollectionsBootstrap).  However, it is broken because of:

- Serialization problem, #254 
- Scala.js 1.0.0-M3 not having a 2.13.0-M5 build

Previously, #217.

**Comment by SethTisue** [comment]
@ashawley looking at https://travis-ci.org/scala/scala-xml/builds/428459277 and at the staging repos on Sonatype, it looks like you hit the same problem I did at https://github.com/scala/scala-parser-combinators/issues/170, where the Travis job for JDK 6 (https://travis-ci.org/scala/scala-xml/jobs/428459278) actually ran on JDK 8, so artifacts got staged twice. there are two staging repos, orgscala-lang-1607 and orgscala-lang-1608 that both contain similar (possibly identical?) artifacts

I think you need to do the equivalent of https://github.com/scala/scala-parser-combinators/pull/156 here. (or if we already did that here but in some other branch, cherry-pick the change)

wdyt, should I just pick one of the two staging repos (1607 and 1608) and release it, or should we redo this, like I did for scala-parser-combinators?

**Comment by ashawley** [comment]
I'm familiar with the issue, it was #246 here.

Sounds like we have two identical JDK 8 artifacts, but I don't know for sure.

Should I just cherry-pick and force-push the tag?

**Comment by SethTisue** [comment]
that seems like the safest course

(well, I'm not actually sure if "force-push the tag" has the same or different effects than deleting it (first push) and then re-creating it (second push), which is what I did on scala-parser-combinators)

**Comment by ashawley** [comment]
Yeah, forcing the tag, then force-push the tag again should have worked.  Can you look again?  Should just have one set of artifacts this time.

**Comment by SethTisue** [comment]
I dropped orgscala-lang-1607 and orgscala-lang-1608 via the Sonatype web UI

and also released orgscala-lang-1609 and orgscala-lang-1610 (as usual it's nondeterministic how many staging repos you end up with, in this case the JVM artifacts were in one and the JS artifacts in the other)

so let's keep an eye out now on https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.13.0-M5/1.1.0/

**Comment by SethTisue** [comment]
happy little artifacts

<img width="733" alt="screen shot 2018-09-14 at 4 59 57 pm" src="https://user-images.githubusercontent.com/161079/45579811-a2e27280-b83f-11e8-8f39-01dfd154dd56.png">

```
Welcome to Scala 2.13.0-M5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_181).
Type in expressions for evaluation. Or try :help.

scala> <foo/>
res0: scala.xml.Elem = <foo/>
```

scala/make-release-notes@17fb353912deb0a9d97ceb51268927c8e6586d23

thanks Aaron!
