### ISSUE TITLE
XhtmlParser throws java.lang.NullPointerException with valid doctype

### ISSUE THREAD

**Issue by mjuopperi** [scala/scala-xml#259]
Parsing the XML below with the code provided produces the following error. Adding a space before the closing `>` (`<!DOCTYPE html >`) makes it work. The doctype without the space is valid according to the [HTML5 spec](https://www.w3.org/TR/html52/syntax.html#the-doctype).

I'm fairly sure the issue is that the parser expects a space [here](https://github.com/scala/scala-xml/blob/master/shared/src/main/scala/scala/xml/parsing/MarkupParser.scala#L521).

```
file:/path/to/file.xml:2:15: whitespace expected<html xmlns="http://www.w3.org/1999/xhtml">              ^
file:/path/to/file.xml:2:15: document must contain exactly one element              ^
java.lang.NullPointerException
	at scala.xml.NodeSeq.toString(test.sc:151)
	at A$A7$.print$$$Worksheet$$$Array$$$(test.sc:38)
	at A$A7$.main(test.sc:27)
	at A$A7.main(test.sc)
	at #worksheet#.#worksheet#(test.sc)
```

```scala
import scala.io.Source
import scala.xml.parsing.XhtmlParser

XhtmlParser(Source.fromFile("/path/to/file.xml", "UTF-8"))
```

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8" />
    </head>
    <body>
        <p>Content</p>
    </body>
</html>
```

**Comment by ashawley** [comment]
Thanks for reporting this.  Seems like it could be fixed easily enough.  I worry we have enough test coverage for this code to avoid a regression.  I'm also skeptical anyone uses this code to parse HTML, evidence of this bug.  However, it is a sub-class of the `ConstructingParser` which likely has more popular usage.

**Comment by ashawley** [comment]
Curiously, the null pointer exception doesn't occur with `Source.fromString`:

```scala
XhtmlParser(Source.fromString(xml))
```

That will make it difficult to unit test.
