### ISSUE TITLE
Travis build is broken

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#272]
OpenJDK6 wouldn't work on Trusty.  I rolled back to Precise in #271, but it didn't work entirely.

I predict [this change at Travis](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration) is what bit us.

**Comment by SethTisue** [comment]
#271 ended up fixing this completely, right?

**Comment by ashawley** [comment]
Yes, it did.
