### ISSUE TITLE
Scala Native Support

### ISSUE THREAD

**Issue by sadhen** [scala/scala-xml#282]

**Comment by SethTisue** [comment]
I believe a pull request on this would be welcome, even if it only supported XML generation and not XML parsing (see https://github.com/scala/scala-xml/issues/198 for discussion on that)

**Comment by SethTisue** [comment]
we've now dropped Scala 2.11 support here in this repo, so I think this would now depend on Scala Native adding support for 2.12

**Comment by sadhen** [comment]
Scala Native 0.4.0 is released! Come back to see if there is a way to have a native scala-xml.

**Comment by david-bouyssie** [comment]
I have ported the missing pieces for a full XML support on SN:
https://github.com/david-bouyssie/xml4s

The following artifact contains a pure Scala Pull Parser (fork of Kxml2), with an adapter for SAX:
https://search.maven.org/artifact/com.github.david-bouyssie/xml4s-xmlpull-api_native0.4_2.13/0.1.0/jar

On the long term it should also solve this similar Scala.js issue https://github.com/scala/scala-xml/issues/198

This work is still in early stage, so feel free to ask for improvements.
