### ISSUE TITLE
Publish for 2.13.0-RC1

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#283]
https://github.com/scala/bug/issues/11471

**Comment by SethTisue** [comment]
related: #276

**Comment by SethTisue** [comment]
are you thinking of publishing 1.2.0 only for RC1, or 1.1.1 only, or both, or what...? should we discuss?

**Comment by SethTisue** [comment]
this is blocking ScalaTest which then blocks big swathes of the ecosystem, so I'm eager to get it resolved quickly now that Scala.js 0.6.27 and 1.0.0-M7 are on Maven Central. let me know if there's pieces of this I can help with or be assigned

**Comment by ashawley** [comment]
Yeah, I was hoping to just release as 1.2.0.  Ok with you?  Release notes are in #287.

**Comment by SethTisue** [comment]
> Ok with you?

Yes, I think we could wait and see if anyone asks for 1.1.1. In the meantime it's a nice nudge to get people to try out 1.2.0.

**Comment by ashawley** [comment]
Yeah, I agree.  If people need 1.1.1 published, then we can try to piece it together.

**Comment by ashawley** [comment]
Updated Maven badge on #289
