### ISSUE TITLE
Publish 1.2.0

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#287]
This is a small bug-fix release, but also includes all the Scala 2.13 changes merged to master in preparation for Scala 2.13.0 final release.

- Various changes for 2.13.0 support #276, #256, #217
- Fix match result for attribute search of empty string #249 
- Fix missing `toString` in `dtd.Decl` #270 
- Remove `name` field in `transform.RewriteRule` #129
- Update Scala.js from 0.6.26 #274 
- Update Scala.js from 1.0.0-M6 #260 
- Update Scala.js to 0.6.27 and 1.0.0-M7 #283 
- Fix license in POM file to Apache License 2.0 #275 

This release is not backwards compatible with the last release of scala-xml, 1.1.1, because of the small change that removes the `name` field from `transform.RewriteRule`, see #129.   It appears to have been an unused vestigial class member in a rarely used class, so it's hopefully of low risk.

**Comment by SethTisue** [comment]
LGTM

**Comment by ashawley** [comment]
Pushed a tag to Travis

**Comment by SethTisue** [comment]
publishing job https://travis-ci.org/scala/scala-xml/builds/516238234 is green

<img width="1336" alt="Screen Shot 2019-04-05 at 4 39 42 PM" src="https://user-images.githubusercontent.com/161079/55639503-6ff2d280-57c1-11e9-80ad-dd17a9ddbf14.png">

hit "close" on all of them

sanity checked list of contents, all expected combinations seem present

hit "release" on all of them

**Comment by SethTisue** [comment]
done! artifacts are on Maven Central
