### ISSUE TITLE
Publish for 2.13.0-RC2

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#311]
A tag was pushed for 1.2.0:

https://github.com/scala/scala-xml/releases/tag/v1.2.0%232.13.0-RC2%238

Artifacts for 2.13.0-RC2 should have shown up in Sonatype.

**Comment by SethTisue** [comment]
I hit "close" and "release" in the Sonatype web UI

**Comment by SethTisue** [comment]
the staging repos contained 2.11, 2.12, and 2.13.0-RC2 artifacts, so when I released them, Sonatype refused to release any of them, since the 2.11 and 2.12 artifacts were duplicates. I had thought it would let the 2.13.0-RC2 ones go forward anyway

can you push a new tag for the RC2 artifacts only?

**Comment by ashawley** [comment]
Weird, I guess there's something wrong with the publish script.

I'll try to just build RC2 artifacts in Travis.

**Comment by SethTisue** [comment]
I see staging repos (I don't get notified, but I happened to look)

they contain only RC2 artifacts :+1:

I hit "close" and "release"

let's keep an eye on https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.13.0-RC2/1.2.0/

**Comment by SethTisue** [comment]
```
% cat build.sbt
scalaVersion := "2.13.0-RC2"
libraryDependencies ++= Seq(
  "org.scala-lang.modules" %% "scala-xml" % "1.2.0",
)
% sbt console
[info] Loading project definition from /Users/tisue/tmp/2.13-libs/project
[info] Loading settings for project root-2-13-libs from build.sbt ...
[info] Set current project to root-2-13-libs (in build file:/Users/tisue/tmp/2.13-libs/)
[info] Starting scala interpreter...
Welcome to Scala 2.13.0-RC2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_202).
Type in expressions for evaluation. Or try :help.

scala> <tada/>
res0: scala.xml.Elem = <tada/>
```
