### ISSUE TITLE
scala-xml repo has sbt console errors 

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#313]
Seems after merging #312, starting the console in sbt causes issues:

```
> console
[info] Starting scala interpreter...
Welcome to Scala 2.12.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_40).
Type in expressions for evaluation. Or try :help.

scala> <console>:5: error: object tools is not a member of package scala
         var value: scala.tools.nsc.interpreter.IMain = _
                          ^
<console>:6: error: object tools is not a member of package scala
         def set(x: _root_.scala.Any) = value = x.asInstanceOf[scala.tools.nsc.interpreter.IMain]
```

If I disable the sbt-dotty plugin, it doesn't happen.

**Comment by SethTisue** [comment]
@smarter your dept, or can you recommend someone else from the Dotty team who could look at it?

**Comment by smarter** [comment]
sbt-dotty tries very carefully to not affect non-dotty projects, but turns out that we're doing it wrong and I don't know if there's a way to do it right: https://gitter.im/sbt/sbt-contrib?at=5cea7db4ad024978c62ff208. I'll look into it.

**Comment by ashawley** [comment]
Thanks for looking into it.  

These aren't fatal errors.  The Scala REPL does seem to work.  However the errors would seem to hint at other problems.  For one, we can no longer use XML literals:

```
scala> <xml/>
<console>:12: error: To compile XML syntax, the scala.xml package must be on the classpath.
Please see https://github.com/scala/scala-xml for details.
       <xml/>
       ^
```

It seems this is because the library code is generally unreachable:

```
scala> scala.xml.XML.loadString("<xml/>")
<console>:12: error: object xml is not a member of package scala
       scala.xml.XML.loadString("<xml/>")
```

Using the JVM sub-project, `xml/console` will work as a workaround:

```
> xml/console
[info] Starting scala interpreter...
Welcome to Scala 2.12.8 (Java HotSpot(TM) 64-Bit Server VM, Java 11.0.2).
Type in expressions for evaluation. Or try :help.

<console>:5: error: object tools is not a member of package scala
         var value: scala.tools.nsc.interpreter.IMain = _
                          ^
<console>:6: error: object tools is not a member of package scala
         def set(x: _root_.scala.Any) = value = x.asInstanceOf[scala.tools.nsc.interpreter.IMain]
                                                                     ^
scala> <xml/>
res0: scala.xml.Elem = <xml/>
```

**Comment by smarter** [comment]
Fixed by https://github.com/scala/scala-xml/pull/314.

**Comment by SethTisue** [comment]
@eed3si9n maybe you should take a gander at https://github.com/dotty-staging/dotty/commit/d46235bc79fbdd0d31d8dbfbbab955ecedea05eb

**Comment by smarter** [comment]
@SethTisue He reviewed the PR already :)

**Comment by eed3si9n** [comment]
@SethTisue Yea. Both Dale and I have reviewed https://github.com/lampepfl/dotty/pull/6577

**Comment by eed3si9n** [comment]
However, I do appreciate the "hey Eugene maybe you should look at this" signals.

**Comment by SethTisue** [comment]
oh sorry, I only looked at the commit without looking at the PR :-)
