### ISSUE TITLE
publish for Scala 2.13.0-RC3

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-xml#316]
@ashawley if you happen to be awake and available, lmk, otherwise I can do it. PR is #315

**Comment by SethTisue** [comment]
PR merged

**Comment by SethTisue** [comment]
@ashawley I see you pushed a tag, but then https://travis-ci.org/scala/scala-xml/builds/538964180 shows as "canceled"?

**Comment by SethTisue** [comment]
I see that the RC2 and RC3 tags are orphan commits (not on any branch that) use `.travis.yml` to cut the matrix down to just RC2/RC3

oh, I see now that's because over at #311 the thing of using the tag name to restrict the Scala versions didn't work

and we're having the same problem over at https://github.com/scala/scala-parser-combinators/issues/214

**Comment by SethTisue** [comment]
is this just how things work now, since https://github.com/scala/scala-xml/pull/223?

**Comment by SethTisue** [comment]
okay, I see now that it is:

```
# In order to build a previously released version against a new (binary incompatible) Scala release,
# a new commit that modifies (and prunes) the Scala versions in .travis.yml needs to be added on top
# of the existing tag. Then a new tag can be created for that commit, e.g., `v1.2.3#2.13.0-M5`.
# Everything after the `#` in the tag name is ignored.
```

**Comment by SethTisue** [comment]
over at https://github.com/scala/scala-parser-combinators/issues/214 we found that the regex in `admin/build.sh` expects the two-`#` format like ``v1.2.3#2.13.0-M5#8`

but in this repo, `admin/build.sh` is different:

```
tagPat="^v$verPat(#.*)?$"
```

so we shouldn't need an extra `#8` at the end

**Comment by SethTisue** [comment]
* commit: 806c4782a63852db0d9bef6ebec47750efbebf7e
* tag: https://github.com/scala/scala-xml/releases/tag/v1.2.0%232.13.0-RC3
* job: https://travis-ci.org/scala/scala-xml/builds/539110052

**Comment by SethTisue** [comment]
staging repos closed, released.

now we keep an eye out at https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.13.0-RC3/1.2.0/

**Comment by SethTisue** [comment]
scala/make-release-notes@0a95e4a2692074571598ecb7e68c6d4b61f36e02

**Comment by ashawley** [comment]
Thanks for getting scala-xml published.  All Travis builds seemed to stall out for me last night, not just the tag.
