### ISSUE TITLE
Publish for 2.13.0

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#319]
https://contributors.scala-lang.org/t/scala-2-13-0-release/3382/2

**Comment by ashawley** [comment]
Pushed a tag:

https://github.com/scala/scala-xml/releases/tag/v1.2.0%232.13.0

**Comment by ashawley** [comment]
Built successfully in Travis:

https://travis-ci.org/scala/scala-xml/builds/542796686

**Comment by SethTisue** [comment]
not sure what happened here, but when I tried to close the staging repos in the Sonatype web UI, I got

```
typeId | sources-staging
-- | --
failureMessage | Missing: no main jar artifact found in folder '/org/scala-lang/modules/scala-xml_sjs1.0.0-M8_2.13/1.2.0'
```

and

```
javadoc-staging
--
failureMessage | Missing: no main jar artifact found in folder '/org/scala-lang/modules/scala-xml_sjs1.0.0-M8_2.13/1.2.0'
```

I don't have time at the moment to investigate further.

Not sure if maybe just trying again might fix it (wouldn't be unheard of with Sonatype stuff, especially when we end up with multiple staging repos because we're publishing so much stuff all at once).

**Comment by ashawley** [comment]
I hit "Restart build" in Travis.  Will that work?  We'll see I guess...

**Comment by ashawley** [comment]
Seems this is a transient error.

https://issues.sonatype.org/browse/OSSRH-46597

> We tried retrying this multiple times and our 4th tried went through.

Hopefully, we don't have to try 4 times.

**Comment by ashawley** [comment]
The entire build was re-run successfully:

https://travis-ci.org/scala/scala-xml/builds/542796686

**Comment by SethTisue** [comment]
closed, released. keep an eye out ? I’m on the go

**Comment by ashawley** [comment]
So far, so good.  Thanks, Seth!

**Comment by SethTisue** [comment]
https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.13/1.2.0/ :+1:
