### ISSUE TITLE
Deprecate scala.xml.persistent?

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#329]
I'd be curious if anyone uses this implementation.  I'm tempted to remove in the forthcoming 2.0 release.

The warnings could be added to a hypothetical 1.3.0 release for Scala 2.12 and 2.13 some time down the road.

**Comment by SethTisue** [comment]
oh I just saw #331 maybe you meant to keep this open for that

**Comment by ashawley** [comment]
That's fine.  I'm not sure why GitHub didn't auto-close.  Maybe because it wasn't merged to master or something?
