### ISSUE TITLE
Use AdoptOpenJDK in the build

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#335]
@eed3si9n opened #334.

What's the rationale for doing this?   Isn't Travis already using OpenJDK?

**Comment by eed3si9n** [comment]
> What's the rationale for doing this?

Lightbend is unifying on using AdoptOpenJDK distribution of OpenJDK for testing because it's available widely, and it's responsibly maintained. sbt, Akka etc have been doing it a while now, and I am just sweeping through scala/* things.

**Comment by SethTisue** [comment]
the change to SDKMAN will hopefully also improve reproducibility, robustness, and up-to-date-ness of the build, since Travis-CI seems to keep changing around what JDKs are supported and also doesn't always keep up with JDK updates

**Comment by SethTisue** [comment]
umbrella ticket is https://github.com/scala/scala-dev/issues/587
