### ISSUE TITLE
Broken test in specs2

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#336]
After applying the fix to #57, there's a strange test in specs2 that is checking the XML output with the result of `scala.xml.Utility.escape`:

https://github.com/etorreborre/specs2/blob/c7bc40bf6c/junit/jvm/src/test/scala/org/specs2/reporter/JUnitXmlPrinterSpec.scala#L94

I knew the XML output of quotation marks would change for users.  I didn't expect tests that would be using `Utility.escape` to validate things.  I'm not sure there is a workaround for this with libraries that need to cross-compile.

**Comment by SethTisue** [comment]
thanks for opening this, it was in my queue to open a ticket myself but I hadn't gotten to it :-)

I think it would be reasonable to ask specs2 to find another way to write the test. /cc @etorreborre

**Comment by ashawley** [comment]
Thanks, Seth.  Fixed in https://github.com/etorreborre/specs2/pull/754.
