### ISSUE TITLE
Milestone release 2.0.0-M1

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#363]
It seems scala-xml may have switched to sbt-dynver plugin at an awkward time.  Previously, the current version in master should have been 2.0.0-SNAPSHOT.  After #356,

    > show xml/version
    [info] 1.2.0+132-bb9b9743-SNAPSHOT

I've never used sbt-dynver, but I understand that once we have a tag for 2.0.x, it might get back to a 2.0 version number.  This might be a good opportunity to publish a milestone release.  Ok to publish a tag for 2.0.0-M1?  Should we publish the artifacts, as well?  Since 1.2.0 was released, there have been some breaking changes in master.  There have been various conservative breaking changes to remove deprecated classes and members.  This is a good opportunity to publish a milestone release.  The benefit of a milestone is that it doesn't commit us to binary compatibility.

**Comment by lrytz** [comment]
Sounds good to me. 

>  Should we publish the artifacts, as well?

I don't see why not!

**Comment by SethTisue** [comment]
publishing a milestone SGTM. (partly because it's an opportunity to make sure everything is set up properly.)

> I've never used sbt-dynver, but I understand that once we have a tag for 2.0.x, it might get back to a 2.0 version number

I don't think sbt-dynver's behavior depends on whether the tags it's looking at have been pushed to any remote, so you should be able to test this locally.

**Comment by ashawley** [comment]
Ok, thanks I'll work on it.  First, I'll try to put together a PR that adds a CHANGLOG.md and adds some notes about 2.0 in the README.md.

**Comment by ashawley** [comment]
Tag pushed for 2.0.0-M1, the build ran on Travis, and published to Sonatype.  There should be a staging repo with the artifacts.

**Comment by SethTisue** [comment]
there were exactly six staging repos, and each one was already closed :+1:

I hit "release"

six and not seven, though — is it intentional that nothing was published for Dotty?

**Comment by lrytz** [comment]
Yes, that's intentional: https://github.com/scala/scala-xml/blob/e2e709f1eb83188f68e0a8dcbe94e3e51b8c8079/build.sh#L17-L24
