### ISSUE TITLE
Add Automatic-Module-Name to MANIFEST.INF

### ISSUE THREAD

**Issue by schrepfler** [scala/scala-xml#367]
In order to increase compatibility on JDK versions with modules consider adding Automatic-Module-Name in the MANIFEST.INF along the lines of akka/akka#23960 or perhaps even implement properly the module-info descriptor.

**Comment by ashawley** [comment]
I predict this may be something that could be handled upstream in the shared sbt plugin https://github.com/scala/sbt-scala-module/

**Comment by schrepfler** [comment]
Ah, wasn't aware there's a shared build plugin. I'll raise it upstream, thanks.

**Comment by ashawley** [comment]
We'll see.  We can keep this open, though.

**Comment by ashawley** [comment]
I don't know enough, but maybe it's even something that would be done in sbt or even Scala itself.

**Comment by SethTisue** [comment]
fixed by #518
