### ISSUE TITLE
SDKMAN is broken in Travis

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#369]
See #368 

```
$ sdk install java $(sdk list java | grep -o "$ADOPTOPENJDK\.[0-9\.]*hs-adpt" | head -1)
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by ashawley** [comment]
Seems like Travis is moving towards this `install-jdk.sh` command for the Java system.

https://docs.travis-ci.com/user/languages/java/

It seems to support AdoptOpenJDK:

https://sormuras.github.io/blog/2018-06-22-jdk-matrix.html

**Comment by SethTisue** [comment]
fyi @eed3si9n

**Comment by lrytz** [comment]
We have a fix in scala/scala, but long term would like to factor out the sdk stuff (https://blog.travis-ci.com/2019-11-11-build-config-imports). Short-term, clearing all travis caches helps (I just did that).
