### ISSUE TITLE
Publish Scala.js artifacts for 1.0.0-RC1

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#373]
https://www.scala-js.org/news/2019/11/26/announcing-scalajs-1.0.0-RC1/

This needs to be done for 1.2.0 series, and possibly should be done for the 2.0.0-M1 milestone of scala-xml.

**Comment by ashawley** [comment]
It didn't work on the `1.x` branch.  Maybe because it still uses sbt 0.13.18?
```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scala-js#sbt-scalajs;1.0.0-RC1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		org.scala-js:sbt-scalajs:1.0.0-RC1 (scalaVersion=2.10, sbtVersion=0.13)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.scala-js:sbt-scalajs:1.0.0-RC1 (scalaVersion=2.10, sbtVersion=0.13) (/home/travis/build/ashawley/scala-xml/project/plugins.sbt#L11-12)
[warn] 		  +- default:scala-xml-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: org.scala-js#sbt-scalajs;1.0.0-RC1: not found
```

**Comment by ashawley** [comment]
Maybe I'll just make the artifacts for 2.0.0-M1...

**Comment by ashawley** [comment]
The build script supports publishing artifacts for an old tag with a new Scala version by adding it to the tag name after a `#`, but it doesn't work for Scala.js targets.

**Comment by ashawley** [comment]
Published the tag `v2.0.0-M1#sjs_1.0.0-RC1` based on the `v2.0.0-M1` tag with logic for publishing Scala.js milestones, which see #376.

**Comment by ashawley** [comment]
https://travis-ci.org/scala/scala-xml/builds/620490656

**Comment by lrytz** [comment]
Maybe this situation is rare enough and we can just create a specific commit for that release? Something like this:
https://github.com/scala/scala-xml/compare/master...lrytz:new-js

Then you could create a tag `v2.0.0-M1#sjs_1.0.0-RC1` (the suffix would be ignored).

**Comment by ashawley** [comment]
Sure, that's true.  And that's what I did.  Please weigh in at #376.

**Comment by ashawley** [comment]
Could someone on the Scala team inspect Sonatype to see if there was a repository published for scala-xml 2.0.0-M1 with just artifacts for Scala.js 1.0.0-RC1?

**Comment by lrytz** [comment]
There are two staging repositories: https://oss.sonatype.org/content/repositories/orgscala-lang-1976/ and https://oss.sonatype.org/content/repositories/orgscala-lang-1977/
Seems to be fine, but please take a look yourself.

**Comment by ashawley** [comment]
Great, thanks.  They look ok to me.  Please publish.

**Comment by lrytz** [comment]
OK, done. Thanks for doing the release!

**Comment by ashawley** [comment]
Thank you!
