### ISSUE TITLE
Publish Dotty builds

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#389]
I've added logic for Dotty to the build script in #387.

There should be two Sonatype repos with Dotty builds, one for 0.20-RC1 and one for 0.21-RC1.

**Comment by lrytz** [comment]
Here are the staging repos:
  - https://oss.sonatype.org/content/repositories/orgscala-lang-2041/
  - https://oss.sonatype.org/content/repositories/orgscala-lang-2039/

Let me know if they should be released.

**Comment by ashawley** [comment]
A smoke test suggests they work:

https://github.com/ashawley/dotty-scala-xml-example

**Comment by ashawley** [comment]
They look good to me.  Could you release?

**Comment by SethTisue** [comment]
I hit "release" in the web UI

**Comment by ashawley** [comment]
Thanks!
