### ISSUE TITLE
Release 1.3.0

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#401]
There was a significant fix in #392 that seems worth making a release for.

There are also some small deprecations we should publicize.

Changes since 1.2.0:

https://github.com/scala/scala-xml/compare/v1.2.0...1.x

Draft release notes:

> - Fixes regression on Scala 2.13, issue #392, concerning the collections implementation for `NodeSeq`
> - Publish for Scala.js 1.0.0
> - Update Scala.js to 0.6.32
> - Update Scala to 2.12.10 and 2.13.1
> - Various unused public classes and methods are deprecated
>   - Deprecate definitions under `scala.xml.persistent`
>     - `CachedFileStorage`
>     - `Index`
>     - `SetStorage`
>   - Deprecate `scala.xml.dtd.impl.PointedHedgeExp`
>   - Deprecate `scala.xml.dtd.Scanner`
>   - Deprecate `scala.xml.dtd.ContentModelParser`
>   - Deprecate `scala.xml.dtd.ElementValidator`
>   - Deprecate `scala.xml.factory.Binder`
>   - Deprecate `scala.xml.parsing.ValidatingMarkupHandler`
> 
> The items deprecated above are already deleted in the 2.0.0-M1 milestone release, which see https://github.com/scala/scala-xml/blob/v2.0.0-M1/CHANGELOG.md

**Comment by ashawley** [comment]
I wonder if we should just wait for Scala.js 1.0?  It should be coming out in a few days.

**Comment by SethTisue** [comment]
(as we were just discussing at https://github.com/scala/scala-xml/issues/408 , I'd be content just doing 2.0.0 and at least provisionally abandoning the 1.x series)

**Comment by ashawley** [comment]
Unfortunately, I predict the  Lift framework will more likely benefit from a 1.3.0 release than a 2.0 milestone: 1) Their build looks like it still supports Scala 2.11 and 2) They likely depend on parts of scala-xml that were deprecated and removed in 2.0 milestone.

**Comment by ashawley** [comment]
I'll try to do my part to make a 1.3.0 release.  If I hit a wall, I probably won't spin my wheels on it for long.

**Comment by ashawley** [comment]
Various updates to the build in https://github.com/scala/scala-xml/pull/411

**Comment by ashawley** [comment]
I've added draft release notes to this issue's description.

**Comment by SethTisue** [comment]
s/Publish Scala.js for/Publish for Scala.js/, otherwise LGTM

**Comment by ashawley** [comment]
I've pushed a v1.3.0 tag to Travis

https://travis-ci.org/scala/scala-xml/builds/646903177

**Comment by ashawley** [comment]
As predicted in #411 , publishing from this old branch didn't work

```
$ admin/build.sh
Releasing 1.3.0 with Scala 2.13.1 on Java version 8.
iv undefined
The command "admin/build.sh" exited with 1.
```

I deleted the tag ad will need to revisit.

**Comment by ashawley** [comment]
Looks like it is the openssl command in the build script:

```
K=$encrypted_6b8d67feaab7_key
IV=$encrypted_6b8d67feaab7_iv
openssl aes-256-cbc -K $K -iv $IV -in admin/secring.asc.enc -out admin/secring.asc -d
```

The `$IV` is empty.

**Comment by lrytz** [comment]
So the relevant changes to back-port seem to be
- https://github.com/scala/scala-xml/pull/356
- https://github.com/scala/scala-xml/pull/358
- https://github.com/scala/scala-xml/commit/976662200d2b66a39928dab6067eb111214d769b
- https://github.com/scala/scala-xml/pull/374

I'm happy to do it, as I also want to push the simplification discussed in https://github.com/scala/scala-xml/pull/406#discussion_r378899224 through all the module repos, but I won't have time within the next few days...

**Comment by lrytz** [comment]
https://github.com/scala/scala-xml/pull/418 backports the build changes to 1.x

**Comment by andreak** [comment]
Any progress on the 1.3.0 release?
This is blocking us from using Lift with Scala-2.13...

**Comment by ashawley** [comment]
Lukas did the heavy lifting of fixing the build on the 1.x branch.

I've pushed a tag for 1.3.0:

https://travis-ci.org/github/scala/scala-xml/builds/663175069

Someone on the Scala team will have to publish.

**Comment by andreak** [comment]
Great!

**Comment by SethTisue** [comment]
artifacts are on their way to Maven Central

**Comment by ashawley** [comment]
Thanks, looks like they made it.

I'll work on pasting the release notes.

**Comment by ashawley** [comment]
https://github.com/scala/scala-xml/releases/tag/v1.3.0

**Comment by ashawley** [comment]
Tweeted:
https://twitter.com/aaron_s_hawley/status/1239726990862802945
