### ISSUE TITLE
Support Scala.js 1.0

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-xml#408]
Scala Steward made an initial stab at https://github.com/scala/scala-xml/pull/407, but it was closed because additional work is needed

**Comment by ashawley** [comment]
Thanks, Seth.  There are two items here.  Releasing 1.2.0 in Scala.js 1.0, and then updating master to Scala.js to 1.0 which Scala Steward attempted.

**Comment by ashawley** [comment]
Scratch that:  I forgot that we can't release from the 1.x branch because of sbt 0.13.

**Comment by SethTisue** [comment]
fwiw, I find the idea of a 2.0.0 release a lot more appealing than doing further 1.x releases. I'm not _opposed_ to any further 1.x releases, I just feel that if we have x amount of maintainer energy to spend, let's spend it on forward motion

(and if anyone appears who really wants/needs further 1.x changes, consider inviting them on board as a maintainer so they can do that themselves)

just throwing an opinion out there. yours trumps mine

**Comment by ashawley** [comment]
I agree.  In fact, the few Scala.js 1.0 milestone users are already using 2.0.0-M1, so it's of no use.

**Comment by SethTisue** [comment]
to argue the other side for a moment though,

one line of reasoning for doing further 1.x releases could be the transitive-dependency situation, e.g. the dependency of scalatest on scala-xml? I haven't really thought this through, but does ScalaTest 3.1 depend on scala-xml 1.x? so if we don't release for Scala.js 1.0, then ScalaTest can't either? that kind of thing?

**Comment by ashawley** [comment]
I've created #410, but also pushed a tag for 2.0.0-M1

https://github.com/scala/scala-xml/releases/tag/v2.0.0-M1#sjs_1.0.0

They should be up on Sonatype in a few minutes:

https://travis-ci.org/scala/scala-xml/jobs/646614052
https://travis-ci.org/scala/scala-xml/jobs/646614056

**Comment by ashawley** [comment]
Strange errors:

```
info] Nexus repository URL: https://oss.sonatype.org/service/local
[info] sonatypeProfileName = org.scala-lang
[info] Preparing a new staging repository for [sbt-sonatype] scala-xml 2.0.0-M1 Scala 2.13.1 Scala.js 1.0.0
[info] Reading staging repository profiles...
[info] Reading staging profiles...
[info] Creating a staging repository in profile org.scala-lang with a description key: [sbt-sonatype] scala-xml 2.0.0-M1 Scala 2.13.1 Scala.js 1.0.0
[info] No staging repository for [sbt-sonatype] scala-xml 2.0.0-M1 Scala 2.13.1 Scala.js 1.0.0 is found
[error] org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 3; The element type "hr" must be terminated by the matching end-tag "</hr>".
```

```
[info] Nexus repository URL: https://oss.sonatype.org/service/local
[info] sonatypeProfileName = org.scala-lang
[info] Preparing a new staging repository for [sbt-sonatype] scala-xml 2.0.0-M1 Scala 2.12.10 Scala.js 1.0.0
[info] Reading staging repository profiles...
[info] Reading staging profiles...
[info] No staging repository for [sbt-sonatype] scala-xml 2.0.0-M1 Scala 2.12.10 Scala.js 1.0.0 is found
[info] Creating a staging repository in profile org.scala-lang with a description key: [sbt-sonatype] scala-xml 2.0.0-M1 Scala 2.12.10 Scala.js 1.0.0
[error] org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 3; The element type "hr" must be terminated by the matching end-tag "</hr>".
```

**Comment by ashawley** [comment]
Gosh, `SAXParseException`!  I guess Scala XML wormholed in to the Sonatype mainframe and tried to add a horizontal rule.  That's the only explanation.  I'm just kidding.

**Comment by ashawley** [comment]
Must be Sonatype is getting slammed.  We can hit restart on those jobs when things quiet down.

**Comment by ashawley** [comment]
> I haven't really thought this through, but does ScalaTest 3.1 depend on scala-xml 1.x?

Yeah, I believe it is on 1.2.0.  

https://github.com/scalatest/scalatest/blob/9d8061c359/project/scalatest.scala#L225

So far, we haven't released any 1.0.0-RCx releases, so I'm not sure how they're fairing.  Although, ScalaTest is usually delayed in finding out these questions.

**Comment by SethTisue** [comment]
no staging repos at https://oss.sonatype.org/#stagingRepositories . yeah, I guess delete and recreate the tag again later and hope for the best

**Comment by ashawley** [comment]
Thanks for dropping them.  I've his restart on two jobs.  It seems they got further along:

```
[info] Nexus repository URL: https://oss.sonatype.org/service/local
[info] sonatypeProfileName = org.scala-lang
[info] Preparing a new staging repository for [sbt-sonatype] scala-xml 2.0.0-M1 Scala 2.12.10 Scala.js 1.0.0
[info] Reading staging repository profiles...
[info] Reading staging profiles...
[info] Creating a staging repository in profile org.scala-lang with a description key: [sbt-sonatype] scala-xml 2.0.0-M1 Scala 2.12.10 Scala.js 1.0.0
[info] No staging repository for [sbt-sonatype] scala-xml 2.0.0-M1 Scala 2.12.10 Scala.js 1.0.0 is found
[info] Created successfully: orgscala-lang-2047
[info] Updating sonatypePublishTo settings...
[info] Set current project to scala-xml (in build file:/home/travis/build/scala/scala-xml/)
[info] Nexus repository URL: https://oss.sonatype.org/service/local
[info] sonatypeProfileName = org.scala-lang
[info] Uploading bundle /home/travis/build/scala/scala-xml/target/sonatype-staging/2.0.0-M1 to https://oss.sonatype.org/service/local/staging/deployByRepositoryId/orgscala-lang-2047/
[info] Finished bundle upload: /home/travis/build/scala/scala-xml/target/sonatype-staging/2.0.0-M1
[info] Updating sonatypePublishTo settings...
[info] Set current project to scala-xml (in build file:/home/travis/build/scala/scala-xml/)
[info] Nexus repository URL: https://oss.sonatype.org/service/local
[info] sonatypeProfileName = org.scala-lang
[info] Reading staging repository profiles...
[info] Closing staging repository [orgscala-lang-2047] status:open, profile:org.scala-lang(1d58d199afe0a) description: [sbt-sonatype] scala-xml 2.0.0-M1 Scala 2.12.10 Scala.js 1.0.0
[info] Reading staging profiles...
[info] Activity open started:2020-02-06T02:09:22.696Z, stopped:2020-02-06T02:10:14.615Z
[info] repositoryCreated: id:orgscala-lang-2047, user:[secure], ip:35.222.7.205
[info] Activity close started:2020-02-06T02:10:20.492Z, stopped:
[info]   Evaluate: id:5e9e8e6f8d20a3, rule:sources-staging
[info]   Evaluate: javadoc-staging
[info]     Passed: javadoc-staging
[info]   Evaluate: no-traversal-paths-in-archive-file
[info]     Passed: no-traversal-paths-in-archive-file
[info]   Evaluate: profile-target-matching-staging
[info]     Passed: profile-target-matching-staging
[info]   Evaluate: checksum-staging
[info]     Passed: checksum-staging
[info]   Evaluate: pom-staging
[info]     Passed: pom-staging
[info]   Evaluate: signature-staging
[info]     Passed: signature-staging
[info]   Evaluate: sources-staging
[info]     Passed: sources-staging
[info]     Passed: id:5e9e8e6f8d20a3
[info] repositoryClosed: id:orgscala-lang-2047
[info] Closed successfully
```

**Comment by SethTisue** [comment]
staging repos released
