### ISSUE TITLE
Literal of NodeBuffer regression in Dotty

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#409]
This was reported upstream, which see https://github.com/lampepfl/dotty/issues/8214

**Comment by ashawley** [comment]
Looks like it will be fixed.  Just need to check in Dotty 0.23.

**Comment by ashawley** [comment]
Adding a test back to Scala compiler in https://github.com/scala/scala/pull/8701

**Comment by SethTisue** [comment]
is it time to close this?

**Comment by ashawley** [comment]
Yes, looks like it was fixed in Dotty 0.23.0-RC1.
