### ISSUE TITLE
Switch to Scala.js 1.x

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#430]
Make it the default in the build, or maybe scala-xml 2.0 will be a good opportunity to just remove 0.6.x from the build.

**Comment by SethTisue** [comment]
fwiw, I would be comfortable simply dropping 0.6 (from any/all branches & releases)

**Comment by SethTisue** [comment]
#443 dropped it from master. on the 1.x branch, I don't care if we drop it proactively, but if it starts causing any trouble, I suggest we consider dropping it there too.
