### ISSUE TITLE
Release 2.0.0 (RC, then final)

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#432]
~~1. Release the #392 fix that has been available in 1.3.0.~~ done in M2
~~1. Drop Scala.js 0.6.x?  See #430~~ done in M2
1. Fix RuleTransformer defect #257 with #421?  (Needs review.)
1. Update CHANGELOG (In particular, the differences are from 1.3.0, not 1.2.0)

**Comment by SethTisue** [comment]
no objection here to dropping sjs 0.6

**Comment by SethTisue** [comment]
I'm building M2 in order to get a Dotty version out, so I've retitled this ticket to be about M3.

**Comment by SethTisue** [comment]
probably makes sense to add 3.0.0-M1 support first: https://github.com/scala/scala-xml/issues/466

**Comment by SethTisue** [comment]
I'm going to roll M3 today in order to get a release out for Scala 3.0.0-M2: https://github.com/scala/scala-xml/issues/471

**Comment by SethTisue** [comment]
I'm going to roll M4 today to release for Scala Native 0.4: #484

**Comment by SethTisue** [comment]
@ashawley are you interested in going RC1?

**Comment by ashawley** [comment]
To be honest, the hope was to fix some of the long-standing bugs in a 2.0, but I haven't had time to go back and do that work.  In that vein, I was considering going with 2.0.0-Mx as long as possible unless something really compelled a 2.0 final.  I haven't had time to contribute or even track the latest developments here, so feel free to cut 2.0 versions if it's useful.

**Comment by SethTisue** [comment]
cool, thanks for the update!

personally I'm content to leave it in milestone limbo for the time being, but once Scala 3.0.0 arrives, I think that might a good time to just say to ourselves "it is what it is" and go RC1 and then final with whatever we have. (and if there turn out to be problems, either volunteers materialize who care enough to fix them, or they don't.)

**Comment by SethTisue** [comment]
an example of the kind of trouble this causes downstream is https://github.com/scalatest/scalatest/issues/1973

maybe we should actually go RC1 earlier? as in, like.... now? in order to be in position to do a final version at around the same time 3.0.0 comes out?

@ashawley I suggest we go RC1 unless you can either 1) concretely commit to make specific changes you want to make within a concrete timeframe, or 2) at least identify what you consider blockers or candidate blockers so we can see if there are volunteers who want to tackle them pronto

**Comment by SethTisue** [comment]
I've now tweeted about this: https://twitter.com/SethTisue/status/1367210760435232769
And also asked for feedback here: https://contributors.scala-lang.org/t/scala-xml-2-0-time-to-go-rc-and-then-final/4917

**Comment by ashawley** [comment]
Yes, I assumed that it would be useful to have a 2.0.0 final for the Scala 3.0 process.  Feel free to do that.

The major fixes I envisioned can just be pushed to a version 3.0 of scala-xml.

**Comment by SethTisue** [comment]
Note that we should land #176 and #177 first unless some serious objection is raised.

**Comment by ashawley** [comment]
The only issue with a 2.0.0 final is fixing #413 which was an attempt to fix an old XML quoting bug, #57.  Might be easiest and best to just roll that back and reopen the bug.

**Comment by rossabaker** [comment]
http4s has upgraded to scala-xml-2 because it was the only way to get Scala 3 support without `withDottyCompat`.  We'll probably be spinning this support off to a satellite repo, so we're not tied to scala-xml's release cycle.  But from our perspective, a 2.0.0 would be very welcome.

**Comment by SethTisue** [comment]
I've merged #176 and #177 and submitted #496 which reverts #279

**Comment by SethTisue** [comment]
afaik, once https://github.com/scala/scala-xml/pull/501 is merged we'll be good to go to do 2.0.0-RC1. I suggest we do that right after Scala 3.0.0-RC2 comes out (since we'll need to be publishing something then anyway).

**Comment by SethTisue** [comment]
3.0.0-RC2 is out. I will roll 2.0.0-RC1 now.

**Comment by SethTisue** [comment]
backpublished 2.0.0-RC1 for Scala 3.0.0-RC3

**Comment by SethTisue** [comment]
Looks like we're done here except for publishing: https://github.com/scala/scala-xml/issues/521
