### ISSUE TITLE
leafTag is unused in PrettyPrinter.scala

### ISSUE THREAD

**Issue by carlpoole** [scala/scala-xml#46]
Was formatting an XML file and noticed that the PrettyPrinter adds closing XML tags to leaf tags instead of retaining it's correct '/>' format. It looks like the class does contain a leafTag function but does not use it.

Issue and potential fix outlined here: http://stackoverflow.com/questions/6044883/scala-xml-prettyprinter-to-format-shorter-node-when-there-is-no-text-in-it

**Comment by ashawley** [comment]
Interesting about the unused `leafTag` function.  The handling of empty elements is not exclusively a pretty-printer thing.  The library generally preserves whether a closed tag or a self-closed tag was used:

```
scala> <node></node>.minimizeEmpty
res0: Boolean = false

scala> <node/>.minimizeEmpty
res1: Boolean = true
```
It seems that the Pretty-printer has inherited this behavior from the standard writer for at least the last 10 years.

I guess this raises, "What is the definition of 'pretty-printing' with respect to empty elements?"  Are they preserved or not?  I suppose this should be configurable in a pretty-printer at the very least.

**Comment by biswanaths** [comment]
Previous discussion on this http://comments.gmane.org/gmane.comp.lang.scala.xml/44 . Also what do other prettyprint ( different tool, language) do ? I.e. do they print <a><a> or <a/> ?

**Comment by SethTisue** [comment]
Sure seems like a bug to me.

**Comment by ashawley** [comment]
I made a commit in #90 that adds a Boolean parameter to {{PrettyPrinter}} that configures whether to minimize empty tags or not.

**Comment by biswanaths** [comment]
Checking why the build is failing.

**Comment by ashawley** [comment]
Thanks @biswanaths!  Turns out [typesafehub/migration-manager](http://github.com/typesafehub/migration-manager/wiki/Sbt-plugin#basic-usage) checks for binary compatibility issues.  I don't have access to openjdk6, but I can try to use an Oracle 6 JDK and see if I can avoid the error.

```
> mimaReportBinaryIssues
[warn] Credentials file /Users/aaronhawley/.ivy2/.credentials does not exist
[info] Resolving org.scala-lang#scala-library;2.11.7 ...
[info] scala-xml: found 1 potential binary incompatibilities
[error]  * method this(Int,Int)Unit in class scala.xml.PrettyPrinter does not have a correspondent in new version
[error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("scala.xml.PrettyPrinter.this")
[trace] Stack trace suppressed: run last *:mimaReportBinaryIssues for the full output.
[error] (*:mimaReportBinaryIssues) scala-xml: Binary compatibility check failed!
[error] Total time: 2 s, completed Feb 10, 2016 10:59:35 AM
```

**Comment by ashawley** [comment]
The optional argument of `minimizeEmpty` for the class's constructor that I introduced has been unrolled instead to an alternate constructor method.  Doing this seemed to quell the migration-manager error seen with the openjdk6 build in Travis.

**Comment by ashawley** [comment]
Merging #90, then the `PrettyPrinter` will have a `minimizeEmpty` argument, that is set to `false`.  I suppose that fixes this issue?  After this fix is released, we can update the StackOverflow post. :)

**Comment by ashawley** [comment]
This fix was released in 1.1.0 today, and I've updated the information on the stackoverflow post.  Thanks for reporting this issue.

**Comment by SethTisue** [comment]
@ashawley #90 was merged, should this be closed?

**Comment by SethTisue** [comment]
haha jinx
