### ISSUE TITLE
Upgrade crossbuild to include Scala 3.0.0-M2

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-xml#466]
Currently our crossbuild includes 0.27.0-RC1.

Volunteer to take a stab at upgrading? It might be easy — 0.27.0-RC1 is not very old.

**Comment by SethTisue** [comment]
oh I forgot @isomarcte has WIP on this at https://github.com/scala/scala-xml/pull/440 — interested in finishing that up now that 3.0.0-M1 is out?

**Comment by isomarcte** [comment]
@SethTisue are we good to close this now that https://github.com/scala/scala-xml/pull/470 is merged?
