### ISSUE TITLE
Publish API documentation

### ISSUE THREAD

**Issue by Jasper-M** [scala/scala-xml#469]
Looks like the API for the most recent version didn't get published.

https://scala.github.io/scala-xml/api/1.3.0/scala/xml/

**Comment by SethTisue** [comment]
@ashawley should we ditch the GitHub.io based publication and just direct people to https://javadoc.io/doc/org.scala-lang.modules/scala-xml_2.13/1.3.0/index.html ? (did we discuss this before?)

**Comment by ashawley** [comment]
I've published 1.3.0 just for completeness.  Yeah, feel free to ditch it.  Just need to stop publishing the apiUrl in `build.sbt` to the scala.github.io address in the 2.0.0-Mx milestone series.

**Comment by SethTisue** [comment]
#472
