### ISSUE TITLE
Scala.js cannot load XML from any source

### ISSUE THREAD

**Issue by frankbe** [scala/scala-xml#473]
As described in #198 (Scala.js cannot load XML from String), it's not possible to use XML.loadString within scala.js. But that also seems to be true for any other load and save method within scala.xml.XML.

The errors are all similar: "Referring to non-existent class org.xml.sax..." and "Referring to non-existent class javax.xml.parsers.SAX..." obviously because of the dependency to sax. 

Is there another way to load xml data without the usage of scala.xml.XML object and SAX?

**Comment by SethTisue** [comment]
I've changed the title of #198 to be broader

**Comment by SethTisue** [comment]
and see also #194 — a pull request updating the README to clearly state the situation would be welcome
