### ISSUE TITLE
Can a scala-js version of this be published?

### ISSUE THREAD

**Issue by hrj** [scala/scala-xml#49]
I am not sure if this is feasible, but a scala-js version of this library would help me a lot, since I have a ton of existing code which I could start using on the client-side immediately.

Thanks,
~ hrj

**Comment by retronym** [comment]
We don't have plans to release a scala-js version of the Scala modules in the near term. Perhaps you could pose your question to the [Scala JS Mailing List](https://groups.google.com/forum/#!forum/scala-js) to see if any work has already been started by the community to bridge Scala's XML syntax to JS.

**Comment by retronym** [comment]
Closing as Won't Fix for now. But we're willing to consider a contribution if it is technically feasible.

**Comment by hrj** [comment]
Checked the ScalaJS ML; this was discussed before but no body published it.

I tried building with scala-js and it worked fine on first attempt! (I had been wary of getting lost in sbt land). I will test it further and try to make a PR. I am not familiar with publishing and have some doubts about code organisation.

### SBT project organisation
The scala-js sbt plugin seems to require a separate (sub) project. For the JVM and JS targets to co-exist, it might require shuffling the scala code into a separate folder, say `shared`, that is used by two sub projects: a JVM project and a JS project.

Ideally, I want to avoid changing the code structure, so I will first try preserving it.

### Publishing
I am not familiar with publishing artifacts to maven, etc. I was able to publish the artifact locally. Will probably leave the rest to the experts.

**Comment by omidb** [comment]
It would be great if you can release ScalaJS version of the lib. It's a Scala module and it should be more flexible than STD lib.

**Comment by SethTisue** [comment]
reopening, not because the Scala team plans to work on it, but in the hopes someone in the community will

**Comment by Atry** [comment]
At the moment, Scala.js with Scala 2.10 does compile XML literals. So I guess it is possible for Scala 2.11+ as well.

**Comment by bbarker** [comment]
With the resulting fix from #109 , curious if it is worth publishing a new release so we can also get a compiled artifact for scala.js.

Not really an issue for this ticket, but would be great to have it mentioned on https://www.scala-js.org/libraries/libs.html once it is published.

**Comment by ashawley** [comment]
Agreed, there is a demand for a published Scala.js artifact of scala-xml.    IMO, there are a few bug fixes unrelated to Scala.js that would be worth including.  They just need to get over the line and in to the release:

https://github.com/scala/scala-xml/wiki/Release-Plans
