### ISSUE TITLE
Do not assume that parser is namespace-unaware

### ISSUE THREAD

**Issue by dubinsky** [scala/scala-xml#506]
[scala.xml.parsing.FactoryAdapter](https://github.com/scala/scala-xml/blob/main/shared/src/main/scala/scala/xml/parsing/FactoryAdapter.scala#L171) assumes that namespace declarations are passed into the `startElement()` methods as `xmlns` attributes, and does not override `startPrefixMapping()` at all.

As a result, Scala XML parsing can not be done using namespace-aware parser, which is needed - for instance - to handle XInclude.

**Comment by ashawley** [comment]
Sounds like a change worth making.  It wouldn't break binary compatibility of a public method, so we could include in 2.1.0 release?  We wouldn't need to wait until a 3.0 release?

**Comment by dubinsky** [comment]
> Sounds like a change worth making. It wouldn't break binary compatibility of a public method, so we could include in 2.1.0 release? We wouldn't need to wait until a 3.0 release?

Probably won't break compatibility. I plan to start on this after the handling of comments and other lexical things is complete.
