### ISSUE TITLE
Do not ignore XML comments when parsing

### ISSUE THREAD

**Issue by dubinsky** [scala/scala-xml#508]
`scala-xml` uses `scala.xml.Comment` to represent XML comments if they are present in  the XML literals, and allows constructing comment nodes explicitly; when parsing XML *not* from a literal, `scala.xml.factory.XMLLoader` does *not* set
an instance of `org.xml.sax.ext.LexicalHandler` as an `"http://xml.org/sax/properties/lexical-handler"` property on the underlying parser, and does *not* provide any factory methods that such lexical handler could call from its `comment()` method.

As a result, comments present in the XML being loaded get ignored.

Are there any plans to fix this?

Thanks!

**Comment by SethTisue** [comment]
There don’t seem to be any other tickets about this.

In general, there aren't "plans" for scala-xml except to keep on merging volunteer pull requests that come in and keep doing releases.

**Comment by mbeckerle** [comment]
We have same problem both with Comment and ProcInstr. Those also seem to be stripped.

**Comment by dubinsky** [comment]
> ... keep on merging volunteer pull requests that come in ...

Here is one then: #549; please take a look ;)

**Comment by ashawley** [comment]
I'll take a look.  Thanks for contributing this.

**Comment by ashawley** [comment]
Since it's new behavior, I guess this could be in a 2.1.0 release of scala-xml.

**Comment by ashawley** [comment]
The patch introduces some non-trivial changes to the the library's core parsing infrastructure, but there's no other way to do it.  It's worth accepting, IMO.  Thanks again for the contributionl
