### ISSUE TITLE
Update CHANGELOG.md

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-xml#524]
It has fallen out of date. Volunteer?

@ashawley do you feel it's still even needed?

**Comment by ashawley** [comment]
Yeah, it doesn't really have a lot of risky changes. Probably not necessary, but I'll try to put something together with the release notes you've written.

**Comment by ashawley** [comment]
Ok, I committed the missing releases, and then rearranged it to represent all the changes of 2.0 since 1.3.0.  

Feel free to revise.
