### ISSUE TITLE
Shut down Gitter room, enable GitHub Discussions?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-xml#526]
traffic in the chat room has been only very sporadic, so I think GitHub Discussions would be a better way to take user questions

**Comment by SethTisue** [comment]
going once, going twice...

**Comment by ashawley** [comment]
That seems like a fine proposal to me.  I have no objection.

**Comment by SethTisue** [comment]
Discussions are enabled.

"Delete this room" on Gitter isn't working for me, nor is the "export room data" option. So I just posted a "THIS ROOM IS CLOSED" notice and linked to this ticket.

**Comment by SethTisue** [comment]
Export-room-data worked this time around. So I deleted the room, and here's the messages archive:
[scala-xml-messages-2021-12-16.ndjson.zip](https://github.com/scala/scala-xml/files/7757709/scala-xml-messages-2021-12-16.ndjson.zip)
