### ISSUE TITLE
versionPolicyCheck fails for scalajs-library

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#551]
After merging #548, the Scala.js upgrade in #547 broke the build.  According to the [release notes](https://www.scala-js.org/news/2021/08/04/announcing-scalajs-1.7.0/), Scala.js 1.7.0 added a `versionScheme` to the artifact.  When sbt-scala-module and sbt-version-policy were upgraded, the scalajs-library was added to the `libraryDependencySchemes` in the build of scala-xml.  For the variety of these reason the build is broken for Scala.js,

```
Incompatibilities with dependencies of scala-xml:2.0.1
  org.scala-js:scalajs-library_2.13: incompatible version change
  from 1.6.0 to 1.7.0 (compatibility: strict semantic versioning)
  Dependencies of module scala-xml:2.0.1+10-1fdceff0+20210828-1836-SNAPSHOT
  break the intended compatibility guarantees 'Compatibility.BinaryAndSourceCompatible'
  You have to relax your compatibility intention by changing the value of versionPolicyIntention.
```

**Comment by ashawley** [comment]
Is this because the sbt-version-policy is set to "binary and source compatible"?

    versionPolicyIntention := Compatibility.BinaryAndSourceCompatible,

Is it because Scala.js never defined a `versionScheme` before?

**Comment by julienrf** [comment]
> Is this because the sbt-version-policy is set to "binary and source compatible"?

Yes, if we want to do a minor update of the scalajs-library, we should also bump the minor version number of scala-xml. This is what is advised in the error message “relax your compatibility intention”:

~~~ scala
versionPolicyIntention := Compatibility.BinaryCompatible
~~~

**Comment by ashawley** [comment]
Ok, so we can relax the setting, then after the minor version is released we can revert back to `BinaryAndSourceCompatible` for the scala-xml 2.1.0 series?

**Comment by julienrf** [comment]
> Ok, so we can relax the setting, then after the minor version is released we can revert back to `BinaryAndSourceCompatible` for the scala-xml 2.1.0 series?

Yes
