### ISSUE TITLE
Publish next release (to publish Scala 3 Native support)

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-xml#596]
note that #592 made some build changes that haven't been tested yet in a releasing context, so this release should be done with some extra care

have any other changes been made since the last release? what should the new version number be?

**Comment by SethTisue** [comment]
here's auto-generated release notes for the proposed release.

@ashawley @dubinsky any opinion on whether these changes merit going to 2.1.0? or should we just call it 2.0.2?

## What's Changed
* Update sbt-version-policy to 1.2.1 by @scala-steward in https://github.com/scala/scala-xml/pull/546
* Update sbt-scalajs, scalajs-compiler, ... to 1.7.0 by @scala-steward in https://github.com/scala/scala-xml/pull/547
* Update sbt-scala-module to 2.4.0 by @scala-steward in https://github.com/scala/scala-xml/pull/548
* Relax versionPolicyIntention to BinaryCompatible by @ashawley in https://github.com/scala/scala-xml/pull/554
* Fix Circle error: 'clang-7' has no installation candidate by @ashawley in https://github.com/scala/scala-xml/pull/555
* Add Scala.js on 3.0.1 to Circle by @ashawley in https://github.com/scala/scala-xml/pull/553
* Do not ignore XML comments when parsing by @dubinsky in https://github.com/scala/scala-xml/pull/549
* Update scala3-library to 3.0.2 by @scala-steward in https://github.com/scala/scala-xml/pull/557
* Do not ignore XML CDATA sections when parsing: by @dubinsky in https://github.com/scala/scala-xml/pull/558
* Update scala-compiler, scala-library to 2.12.15 by @scala-steward in https://github.com/scala/scala-xml/pull/563
* in with GitHub Actions, out with Travis-CI by @SethTisue in https://github.com/scala/scala-xml/pull/564
* AdoptOpenJDK is now Temurin by @SethTisue in https://github.com/scala/scala-xml/pull/565
* Update sbt-scalajs, scalajs-compiler, ... to 1.7.1 by @scala-steward in https://github.com/scala/scala-xml/pull/566
* remove unused settings in CircleCI config by @xuwei-k in https://github.com/scala/scala-xml/pull/570
* Update auxlib, javalib, junit-runtime, ... to 0.4.1 by @scala-steward in https://github.com/scala/scala-xml/pull/569
* Update junit-interface to 0.13.2 by @scala-steward in https://github.com/scala/scala-xml/pull/572
* Update Scala 3.1.0 by @scala-steward in https://github.com/scala/scala-xml/pull/568
* Update scala-compiler, scala-library to 2.13.7 by @scala-steward in https://github.com/scala/scala-xml/pull/573
* Set the Circle instance size to small by @ashawley in https://github.com/scala/scala-xml/pull/575
* Update scala-native to 0.4.2 by @scala-steward in https://github.com/scala/scala-xml/pull/576
* Update sbt to 1.5.6 by @scala-steward in https://github.com/scala/scala-xml/pull/578
* Update sbt-scalajs, scalajs-compiler, ... to 1.8.0 by @scala-steward in https://github.com/scala/scala-xml/pull/577
* Parse nodes before and after the root element by @dubinsky in https://github.com/scala/scala-xml/pull/560
* Update sbt to 1.5.7 by @scala-steward in https://github.com/scala/scala-xml/pull/579
* Update sbt to 1.5.8 by @scala-steward in https://github.com/scala/scala-xml/pull/580
* Update sbt to 1.6.0 by @scala-steward in https://github.com/scala/scala-xml/pull/581
* Update sbt to 1.6.1 by @scala-steward in https://github.com/scala/scala-xml/pull/583
* Drop .conf file for Scalafmt by @ashawley in https://github.com/scala/scala-xml/pull/585
* Update junit-interface to 0.13.3 by @scala-steward in https://github.com/scala/scala-xml/pull/582
* Update sbt-scala-module to 3.0.1 by @scala-steward in https://github.com/scala/scala-xml/pull/586
* Update scala-compiler, scala-library to 2.13.8 by @scala-steward in https://github.com/scala/scala-xml/pull/588
* Update scala-native to 0.4.3 by @scala-steward in https://github.com/scala/scala-xml/pull/589
* Update sbt to 1.6.2 by @scala-steward in https://github.com/scala/scala-xml/pull/591
* Update sbt-scalajs, scalajs-compiler, ... to 1.9.0 by @scala-steward in https://github.com/scala/scala-xml/pull/594
* Handle XML namespace declarations even when the underlying parser is … by @dubinsky in https://github.com/scala/scala-xml/pull/587
* Update sbt-header to 5.6.5 by @scala-steward in https://github.com/scala/scala-xml/pull/593
* Update scala3-library, ... to 3.1.1 by @scala-steward in https://github.com/scala/scala-xml/pull/590
* Update auxlib, javalib, junit-runtime, ... to 0.4.4 by @scala-steward in https://github.com/scala/scala-xml/pull/595
* Support Scala Native - Scala 3 by @lolgab in https://github.com/scala/scala-xml/pull/592

## New Contributors
* @dubinsky made their first contribution in https://github.com/scala/scala-xml/pull/549

**Full Changelog**: https://github.com/scala/scala-xml/compare/v2.0.1...v2.0.2

**Comment by dubinsky** [comment]
> @ashawley @dubinsky any opinion on whether these changes merit going to 2.1.0? or should we just call it 2.0.2?

I think when my changes were reviewed @ashawley mentioned that they fit into 2.0.2...

**Comment by catap** [comment]
@SethTisue maybe move forward with it? This is a blocker for https://github.com/scalatest/scalatest/issues/2097 which is blocking scalatests for scala-native for scala 3+

**Comment by SethTisue** [comment]
better release notes:

## What's Changed
* Do not ignore XML comments when parsing by @dubinsky in https://github.com/scala/scala-xml/pull/549
* Do not ignore XML CDATA sections when parsing: by @dubinsky in https://github.com/scala/scala-xml/pull/558
* Parse nodes before and after the root element by @dubinsky in https://github.com/scala/scala-xml/pull/560
* Handle XML namespace declarations even when the underlying parser is … by @dubinsky in https://github.com/scala/scala-xml/pull/587
* Support Scala Native - Scala 3 by @lolgab in https://github.com/scala/scala-xml/pull/592

## Version Bumps 
* Update Scala 3.1.0 by @scala-steward in https://github.com/scala/scala-xml/pull/568
* Update auxlib, javalib, junit-runtime, ... to 0.4.1 by @scala-steward in https://github.com/scala/scala-xml/pull/569
* Update auxlib, javalib, junit-runtime, ... to 0.4.4 by @scala-steward in https://github.com/scala/scala-xml/pull/595
* Update junit-interface to 0.13.2 by @scala-steward in https://github.com/scala/scala-xml/pull/572
* Update junit-interface to 0.13.3 by @scala-steward in https://github.com/scala/scala-xml/pull/582
* Update sbt to 1.5.6 by @scala-steward in https://github.com/scala/scala-xml/pull/578
* Update sbt to 1.5.7 by @scala-steward in https://github.com/scala/scala-xml/pull/579
* Update sbt to 1.5.8 by @scala-steward in https://github.com/scala/scala-xml/pull/580
* Update sbt to 1.6.0 by @scala-steward in https://github.com/scala/scala-xml/pull/581
* Update sbt to 1.6.1 by @scala-steward in https://github.com/scala/scala-xml/pull/583
* Update sbt to 1.6.2 by @scala-steward in https://github.com/scala/scala-xml/pull/591
* Update sbt-header to 5.6.5 by @scala-steward in https://github.com/scala/scala-xml/pull/593
* Update sbt-scala-module to 2.4.0 by @scala-steward in https://github.com/scala/scala-xml/pull/548
* Update sbt-scala-module to 3.0.1 by @scala-steward in https://github.com/scala/scala-xml/pull/586
* Update sbt-scalajs, scalajs-compiler, ... to 1.7.0 by @scala-steward in https://github.com/scala/scala-xml/pull/547
* Update sbt-scalajs, scalajs-compiler, ... to 1.7.1 by @scala-steward in https://github.com/scala/scala-xml/pull/566
* Update sbt-scalajs, scalajs-compiler, ... to 1.8.0 by @scala-steward in https://github.com/scala/scala-xml/pull/577
* Update sbt-scalajs, scalajs-compiler, ... to 1.9.0 by @scala-steward in https://github.com/scala/scala-xml/pull/594
* Update sbt-version-policy to 1.2.1 by @scala-steward in https://github.com/scala/scala-xml/pull/546
* Update scala-compiler, scala-library to 2.12.15 by @scala-steward in https://github.com/scala/scala-xml/pull/563
* Update scala-compiler, scala-library to 2.13.7 by @scala-steward in https://github.com/scala/scala-xml/pull/573
* Update scala-compiler, scala-library to 2.13.8 by @scala-steward in https://github.com/scala/scala-xml/pull/588
* Update scala-native to 0.4.2 by @scala-steward in https://github.com/scala/scala-xml/pull/576
* Update scala-native to 0.4.3 by @scala-steward in https://github.com/scala/scala-xml/pull/589
* Update scala3-library to 3.0.2 by @scala-steward in https://github.com/scala/scala-xml/pull/557
* Update scala3-library, ... to 3.1.1 by @scala-steward in https://github.com/scala/scala-xml/pull/590

## Internal
* Relax versionPolicyIntention to BinaryCompatible by @ashawley in https://github.com/scala/scala-xml/pull/554
* Fix Circle error: 'clang-7' has no installation candidate by @ashawley in https://github.com/scala/scala-xml/pull/555
* Add Scala.js on 3.0.1 to Circle by @ashawley in https://github.com/scala/scala-xml/pull/553
* in with GitHub Actions, out with Travis-CI by @SethTisue in https://github.com/scala/scala-xml/pull/564
* AdoptOpenJDK is now Temurin by @SethTisue in https://github.com/scala/scala-xml/pull/565
* remove unused settings in CircleCI config by @xuwei-k in https://github.com/scala/scala-xml/pull/570
* Set the Circle instance size to small by @ashawley in https://github.com/scala/scala-xml/pull/575
* Drop .conf file for Scalafmt by @ashawley in https://github.com/scala/scala-xml/pull/585

## New Contributors
* @dubinsky made their first contribution in https://github.com/scala/scala-xml/pull/549

According to `git shortlog -sn --no-merges v2.0.1..`, 7 people contributed. Thank you Scala Steward, Aaron S. Hawley, Leonid Dubinsky, Seth Tisue, Julien Richard-Foy, Kenji Yoshida, Lorenzo Gabriele.

**Full Changelog**: https://github.com/scala/scala-xml/compare/v2.0.1...v2.0.2

**Comment by SethTisue** [comment]
a 2.0.2 release job failed with:

```
[error] Module scala-xml has an invalid version number: 2.0.2. You must increment the minor version number to publish a source incompatible release.
(https://github.com/scala/scala-xml/runs/5739371440?check_suite_focus=true#step:4:18)
[error] Module scala-xml has an invalid version number: 2.0.2. You must increment the minor version number to publish a source incompatible release.
(https://github.com/scala/scala-xml/runs/5739371440?check_suite_focus=true#step:4:19)
[error] Module scala-xml has an invalid version number: 2.0.2. You must increment the minor version number to publish a source incompatible release.
(https://github.com/scala/scala-xml/runs/5739371440?check_suite_focus=true#step:4:20)
[error] (xmlJS / versionCheck) Module scala-xml has an invalid version number: 2.0.2. You must increment the minor version number to publish a source incompatible release.
(https://github.com/scala/scala-xml/runs/5739371440?check_suite_focus=true#step:4:21)
[error] (xml / versionCheck) Module scala-xml has an invalid version number: 2.0.2. You must increment the minor version number to publish a source incompatible release.
(https://github.com/scala/scala-xml/runs/5739371440?check_suite_focus=true#step:4:22)
[error] (xmlNative / versionCheck) Module scala-xml has an invalid version number: 2.0.2. You must increment the minor version number to publish a source incompatible release.
(https://github.com/scala/scala-xml/runs/5739371440?check_suite_focus=true#step:4:23)
```

**Comment by SethTisue** [comment]
Volunteer to suggest what the appropriate solution is here and PR a fix...? I cannot spare the time this week or next.

**Comment by catap** [comment]
@SethTisue I guess the root cause is tag `2.0.2` which was added to the last commit on a master branch. Maybe if you remove it and re-run, it will be fine?

**Comment by catap** [comment]
Wired, this line from https://github.com/scalacenter/sbt-version-policy/blob/v1.2.1/sbt-version-policy/src/main/scala/sbtversionpolicy/SbtVersionPolicySettings.scala#L226 which was removed as part of https://github.com/scala/scala-xml/pull/548

**Comment by nightscape** [comment]
The lazy option would be to just bump to 2.1.0 😬 
Would that hurt, except that people need to skim the release notes to see that nothing breaks with the upgrade?

**Comment by catap** [comment]
@nightscape an another way is switch `ThisBuild / versionPolicyIntention` to `Compatibility.BinaryAndSourceCompatible` but I don't think that it is good idea because it has remark that it shouldn't be switched back until `2.1.0` is released: https://github.com/scala/scala-xml/blob/main/build.sbt#L70

Thus, `build.sbt` contains a few hacks which should be removed for the next release and I've just upened a PR to do so: https://github.com/scala/scala-xml/pull/598

@SethTisue any chance to release it as `2.1.0` what should unblock scalatests for scala3 at scala-native?

**Comment by SethTisue** [comment]
I'm happy to go along with whatever the consensus here appears to be. At the moment, #598 is failing CI, so that needs to be fixed first.

(I'm trying to minimize my involvement here to pushing whatever release tag y'all tell me to push — if another maintainer isn't available to push one theirselves, which would be my first choice. Any of y'all interested in joining the volunteer maintainer crew here?)

**Comment by catap** [comment]
@SethTisue to fix my branch you (or someone else) must to remove tag v2.0.2 from GitHub.

as soon as you did it, my PR should work

**Comment by SethTisue** [comment]
That I can do :-)

I deleted the tag and closed/reopened the PR which made the actions re-run, but isn't re-running the CircleCI jobs. I don't know anything about CircleCI (and since @ashawley has been a lot less active lately, maybe we should just remove that stuff, since he was the one managing it); perhaps you'll need to push a commit with a different hash in order to make that part re-run.

**Comment by catap** [comment]
@SethTisue base on that is failed in #598 I believe that now you must release `2.1.0` without this PR. Can you try? It should be releassed fine.

As soon as `2.1.0` is here I'll rebases my PR and it should pass the test.

(Checks and versioning and release process of `scala-xml` quite ugly and wired to be honest)

**Comment by SethTisue** [comment]
https://github.com/scala/scala-xml/releases/tag/v2.1.0, publish job at https://github.com/scala/scala-xml/actions/runs/2088914876

> (Checks and versioning and release process of scala-xml quite ugly and wired to be honest)

Release process seems clean to me, courtesy of sbt-ci-release, but if you have specific suggestions, perhaps they'd be accepted.

As for the checks and versioning aspect, that's coming directly from https://github.com/scalacenter/sbt-version-policy, unless you see some repo-specific aspect here in this repo that could be improved. If it's about sbt-version-policy, you might consider lodging that feedback as one or more tickets there. (cc @julienrf)

**Comment by catap** [comment]
@SethTisue I see.

I mean that mix `sbt-version-policy` and versioning from git's tag with introducing supporting of scala 3 at scala-native creates sort of mess.

Anyway, now it should be much better.

**Comment by SethTisue** [comment]
https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_native0.4_3/2.1.0/ 🎉

thanks all who participated
