### ISSUE TITLE
Re-enable versionPolicyCheck

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#617]
Discussing https://github.com/scala/bug/issues/12632 I was reminded that the Mima plugin and the sbt-version-policy plugin was relaxed and put back and relaxed again a couple of times:

* #551 
* #598
* #604

It should probably be turned back on or at the very least conditionally so.

Currently it is:

```scala
    // should be reverted to Compatibility.BinaryAndSourceCompatible after 2.2.0 is released
    versionPolicyIntention := Compatibility.None,
```

**Comment by ashawley** [comment]
I'm less familiar with the build, but I believe:

1. it should be able to be turned back on for Java, 
2. but can only be `BinaryCompatible` for Scala.js
3. and can't be checked for Native.

**Comment by SethTisue** [comment]
agree
