### ISSUE TITLE
Drop support for Scala 2.11?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-xml#646]
Scala.js and Scala Native have dropped support, so maybe now it's time.

If some really critical bugfix ends up being needed on 2.11, we could always do it from a branch — especially if a volunteer who cares about 2.11 is willing to do the work.

**Comment by SethTisue** [comment]
see also https://github.com/scala/scala-parser-combinators/pull/504

**Comment by dubinsky** [comment]
I'm in favor!

**Comment by SethTisue** [comment]
https://contributors.scala-lang.org/t/lets-drop-scala-2-11-support-from-scala-xml-and-scala-parser-combinators/6080

**Comment by Philippus** [comment]
I think scala 2.11 was already dropped in https://github.com/scala/scala-xml/commit/20b8db223dfc8f1b6fba6d6a34057c0b82be57c5. The last release for scala 2.11 was 1.3.0.

**Comment by SethTisue** [comment]
oh, silly me :-)
