### ISSUE TITLE
Unused value warnings for XML literals starting with Scala 2.13.9

### ISSUE THREAD

**Issue by BennyMcBenBen** [scala/scala-xml#650]
If I am using XML literals, then I am seeing compile warnings starting with Scala version 2.13.9. I am using the sbt-tpolecat plugin so these are actually compile errors for me.

Example:

```scala
import scala.xml.Elem

case class ToDoItem(name: String) {
  def toXml: Elem = {
    <to-do-item>
      <name>{name}</name>
    </to-do-item>
  }
}
```

Compile errors:
```
[error] ToDoItem.scala:5:5: unused value of type scala.xml.NodeBuffer (add `: Unit` to discard silently)
[error]     <to-do-item>
[error]     ^
[error] /ToDoItem.scala:6:7: unused value of type scala.xml.NodeBuffer (add `: Unit` to discard silently)
[error]       <name>{name}</name>
```

Is this a bug or are the new unused warnings incompatible with XML literals? What do you recommend? Thank you.

**Comment by lrytz** [comment]
The issue here is in the compiler (code it generates for XML literals), not in the xml library. Existing ticket: https://github.com/scala/bug/issues/12658

**Comment by som-snytt** [comment]
Reopening in order to close it.
