### ISSUE TITLE
We are missing wiki for this repository 

### ISSUE THREAD

**Issue by biswanaths** [scala/scala-xml#68]
Hey All, 

We don't have wiki entry for this repo. 

Please do suggest an outline and if possible patches to build the wiki. If it existed anywhere else on the nets, let us know, so that we can replicate over here. 

Thanks.

**Comment by biswanaths** [comment]
One possible source(https://scala.contractors/xml_processing_in_scala.pdf) . I personally like this. If other feel nice, we can base the wiki based on this, obviously with permission from the original authors. Please let me know if you know any other source.

**Comment by ashawley** [comment]
Closing in favor of #162

**Comment by SethTisue** [comment]
on the desirability of using a wiki for this, I've summarized my feelings (I'm against it) at https://github.com/typesafehub/migration-manager/issues/199#issuecomment-333619457
