### ISSUE TITLE
Roll a 2.2 release

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-xml#681]
as per email discussion, primary motivation is to ship #677, since that's arguably a security issue. but there are other changes that it is good to ship

we took the Scala 3.3 upgrade, so that's a minor version bump right there

Lukas tried publishing (https://github.com/scala/scala-xml/releases/tag/v2.2.0) but hit some GPG problem (failed run:
https://github.com/scala/scala-xml/actions/runs/5452538547)... probably need to make new secrets

after 2.2 is sorted, we should also do a 1.x release

**Comment by SethTisue** [comment]
replacing the SONATYPE_USERNAME and SONATYPE_PASSWORD secrets on GitHub seems have done the trick: https://github.com/scala/scala-xml/actions/runs/5452538547/jobs/10052110512

leaving the ticket open until artifacts show up on Maven Central, e.g. https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_3/2.2.0/scala-xml_3-2.2.0.jar

**Comment by SethTisue** [comment]
fyi @lrytz

**Comment by mkurz** [comment]
> after 2.2 is sorted, we should also do a 1.x release

@SethTisue it would be really nice if you could backport #677 and do a 1.x release, thank you very much in advance!

**Comment by SethTisue** [comment]
Lukas is looking into how hard that would be

**Comment by mkurz** [comment]
Thanks, would be really nice.
