### ISSUE TITLE
Publish an artifacts for Scala-Native-0.5.0-RC2

### ISSUE THREAD

**Issue by catap** [scala/scala-xml#713]
Folks,

Scala-Native has released 0.5.0-RC2 which is bionarry incompatibly with previus artifacts.

Missed version of scala-xml is kind of blocker for publishing scalatests for SN-0.5.0-RC2, and this two things should allow to start widly test the new release of SN that should allow to catch some new bugs before it was released.

I've tested publishing locally, and it works quite well.

So, here the question: can anyone publish artifacts for scala-xml-2.2.0 for SN-0.5.0-RC2?

Thanks.

**Comment by SethTisue** [comment]
yes, I can do this next week.

**Comment by catap** [comment]
@SethTisue thanks! Also, I think that it wise to make the same for different scala projects like https://github.com/scala/scala-parallel-collections and https://github.com/scala/scala-parser-combinators.

Thanks in advance!

**Comment by SethTisue** [comment]
It seems I misunderstood here — a PR is needed to do the upgrade, first. Once that's been merged, I can pull the publishing levers.

If you want the other projects published, please open tickets in those repos.

**Comment by SethTisue** [comment]
looks like RC3 just came out, btw

**Comment by catap** [comment]
@SethTisue ok, I'll do a PR as soon as it releases. To avoid release for -RC version.

**Comment by SethTisue** [comment]
ticket for 0.5 publishing: https://github.com/scala/scala-xml/issues/717
