### ISSUE TITLE
Publish for Scala Native 0.5

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-xml#717]
with #716 merged this should be good to go

**Comment by SethTisue** [comment]
GPG key had expired; I made a new one (following the sbt-ci-release README, as usual) and updated the secrets

**Comment by SethTisue** [comment]
https://github.com/scala/scala-xml/releases/tag/v2.2.1
https://github.com/scala/scala-xml/actions/runs/8693545682
https://repo1.maven.org/maven2/org/scala-lang/modules/

**Comment by catap** [comment]
Yahoo!, Thanks!
