### ISSUE TITLE
CI integration (nightly and PR validation)

### ISSUE THREAD

**Issue by dragos** [scala/scala-xml#8]
The IDE build depends on Scala modules, and without nightlies or PR validation we can regress in a module release.

**Comment by SethTisue** [comment]
this is now adequately covered by Travis, isn't it?

**Comment by biswanaths** [comment]
https://travis-ci.org/scala/scala-xml/builds  is travis build history for every commit. 

I can't find any nightlies builds or test integration builds.

**Comment by SethTisue** [comment]
another piece of the CI picture is that the [community build](https://github.com/scala/community-builds) builds and tests the latest scala-xml commits (and not just in isolation, but in the context of every project in the build that uses XML).

**Comment by ashawley** [comment]
@SethTisue Can this be closed?  Are community-builds able to give fair warning when commits here at scala-xml are going to negatively affect downstream users?

**Comment by SethTisue** [comment]
> Are community-builds able to give fair warning when commits here at scala-xml are going to negatively affect downstream users

with the possible exception of ScalaIDE, I think so, yes. closing.

re: ScalaIDE, pinging @sschaef @wpopielarski — you can take it up or not as you see fit

**Comment by SethTisue** [comment]
> scala-xml gets built with a released compiler, not with a bleeding-edge compiler

note that this was fixed a while back
