### ISSUE TITLE
Sbt is not able to build with java 1.7 

### ISSUE THREAD

**Issue by biswanaths** [scala/scala-xml#86]
On a system with java 1.7, sbt is not able to figure which scala version to use. The reason are the following line from build.sbt. As you can see there is no condition for java 1.7, and it gives the error "don'know what Scala versions to build on $java". Please see https://github.com/scala/scala-xml/blob/master/build.sbt#L11
 
```
crossScalaVersions         := {
  val java = System.getProperty("java.version")
  if (java.startsWith("1.6."))
    Seq("2.11.7", "2.12.0-M1")
  else if (java.startsWith("1.8."))
    Seq("2.12.0-M2")
  else
    sys.error(s"don't know what Scala versions to build on $java")
}
```

**Comment by SethTisue** [comment]
Note that any change must interact properly with `.travis.yml`; see https://github.com/scala/scala-xml/commit/38fbbbeeff6bc97c4438e3e37041894c93538e46.

I guess it should lump 1.7 in with 1.6? (And, while we're at it, lump 1.9 in with 1.8?)

**Comment by biswanaths** [comment]
@SethTisue , Can you expand " change must interact properly with .travis.yml"  ?

If  we add a condition for java1.7 I don't even see a problem with test we are not even testing for java 1.7.  Also is there a reason, why tests1.7 are removed.

I will go ahead and 1.7 to 1.6 and 1.9 to 1.8 .

**Comment by SethTisue** [comment]
there would only be a problem with `.travis.yml` if someone were contemplating a more drastic change to the `crossScalaVersions` logic.

> is there a reason, why tests1.7 are removed

it just seemed like overkill (slower feedback from Travis, and probably no gain., but I don't have a strong feeling about it one way or the other. you could re-enable it if you see value in it.

**Comment by biswanaths** [comment]
Ok, submitted a pr for the same. 

1.9 already. I hardly know anything about 1.8.
