### ISSUE TITLE
Create and publish release v1.0.6

### ISSUE THREAD

**Issue by biswanaths** [scala/scala-xml#97]
Things to do before release 

- Release draft, find it here https://github.com/scala/scala-xml/releases/edit/untagged-3389094b9a5a81b5e242

- Bump version in build.sbt (Already done https://github.com/scala/scala-xml/commit/c09fc072a77354bd3fe5073da4e53abeb2d11e8c)

- Post release Bump version for the next release

@SethTisue , @adriaanm , @ashawley Please do let me know, if I am missing anything for the release.

**Comment by ashawley** [comment]
@biswanaths Happy to review, but I can't see draft releases it seems.

**Comment by adriaanm** [comment]
Here's the draft. Is it time to add @ashawley to the committers team, @biswanaths? :-)

The following changes have been incoporated in this release 

- Administrative:
 - Remove stale branch, wip/jsuereth-use-module-plugin
 - Update crossScalaVersions to 2.11.8 from 2.11.7
 - Update crossScalaVersions to 2.12.0-M3 from 2.12.0-M1 and 2.12.0-M2
 - Change mimaPreviousVersion in build.sbt to more recent scala-xml than 1.0.1
 - Ask Scala compiler to update versions.properties to next release of scala-xml

- Following issues has been fixed and enhancements are been made:
 - Merged #67 Travis container changes
 - Merged #69, #70, #80 README updates
 - Merged #78 Add more unit tests for #43
 - Merged #81 Use NodeSeq.fromSeq
 - Merged #84 Remove final keyword from scala.xml.MetaData per FIXME
 - Merged #59 Exponential complexity in BasicTransformer fixing #58
 - Merged #87 Enable SBT builds for Java 1.7 and 1.9
 - Merged #88 Unit test for verifying complexity in #59
 - Merged #91 Empty xmlns attribute fixes #45
 - Merged #92 Fix #35 OOM on malformed input

This release was made possible by contributions from @SethTisue,@adriaanm, @ashawley, @lrytz, @som-snytt. 
We would like to thank them for their help.

**Comment by adriaanm** [comment]
Those are some nice release notes! Looks like you're all set for v1.0.6! Once you publish the release, the commit will be tagged and travis will stage a release on sonatype. Let me know when it's done so I can push the button to promote the staging repo to maven central.

**Comment by som-snytt** [comment]
Thanks for the mention, @adriaanm . I didn't have the gumption to adopt the module, but it's nice to see folks step up who can also exercise it!

**Comment by ashawley** [comment]
@biswanaths Release notes look good!

All the items under "Administrative" are TBD -- they're not done yet.  I only proposed those things.  Sorry if that wasn't clear.  Were you planning on doing them?

**Comment by adriaanm** [comment]
@som-snytt, I'd love to take credit, but I didn't write the release notes, was just pasting them. @biswanaths wrote them

**Comment by som-snytt** [comment]
Thanks @biswanaths ! What conscientiousness! Except for the part about not pasting the release notes. Just kidding!

**Comment by lespea** [comment]
Any update on getting this released?

**Comment by biswanaths** [comment]
I would like to address this https://github.com/scala/scala-xml/pull/99 before pushing the release. Seems we are missing some paths for the OOM fix. Hopefully in couple of days.

**Comment by lespea** [comment]
Oh yeah that seems like a good plan.  Thanks for the update!

**Comment by ashawley** [comment]
> Change mimaPreviousVersion in build.sbt to more recent scala-xml than 1.0.1

I tried making this change in #98, but it didn't ended up going very smoothly for reasons I don't understand.  It's not a blocker for the next release, though.

**Comment by ashawley** [comment]
Ok, I resolved the issue with Mima by adding a commit to #98 that fixed it.  I'd say we are good to release a new version of scala-xml once #98 and #100 are merged!

**Comment by devisaneer** [comment]
Any ETA when this release due out in the wild? Keen to see #59 & #99 get out there. Looks like most things are ready to go. TIA

**Comment by sarahgerweck** [comment]
Like @devisaneer, I'd love to see this as well: the fix to #45 / #91 is something that would be quite useful for my project.

**Comment by EdgeCaseBerg** [comment]
Really looking forward to seeing #58 resolved! Is this going to be released soon?

**Comment by SethTisue** [comment]
@biswanaths do you need help? perhaps some of the people commenting on this ticket could help you.

**Comment by biswanaths** [comment]
@SethTisue , let me get through this.

**Comment by biswanaths** [comment]
Really sorry for lot any and all for this inordinate delay. 

I am restarted to work on this. Please do expect a release in couple of days.

**Comment by biswanaths** [comment]
Merged #98 and #100 . 

Thanks again Aaron. Only if each of my thank was a dollar, Aaron would be a millionaire.

**Comment by ashawley** [comment]
Excellent!  Thank you, @biswanaths!  Looking forward to the release.

**Comment by biswanaths** [comment]
@adriaanm , @SethTisue Can any of you help with
" Ask Scala compiler to update versions.properties to next release of scala-xml" ?

**Comment by SethTisue** [comment]
tracking as https://github.com/scala/scala-dev/issues/227. we'll get it in 2.12.1, assuming the 1.0.6 release goes well

**Comment by biswanaths** [comment]
@adriaanm , https://github.com/scala/scala-xml/releases/tag/v1.0.6

Do I need to do anything else ? As mentioned previously can you help us pushing this to maven central ?

**Comment by ashawley** [comment]
@biswanaths Seems like #108 could be merged and added to 1.0.6.  What do you think?

**Comment by biswanaths** [comment]
@ashawley Sure enough. Already did a merge. I think have to look into creating new tag and release.

**Comment by SethTisue** [comment]
> Do I need to do anything else ? As mentioned previously can you help us pushing this to maven central ?

it's already there. if you look at https://travis-ci.org/scala/scala-xml/builds , you'll see an entry for the `v1.0.6` tag, with two runs inside it, the JDK 6 run https://travis-ci.org/scala/scala-xml/jobs/160379375 and the JDK 8 run https://travis-ci.org/scala/scala-xml/jobs/160379376

at the end of the run logs you'll see a bunch of lines like

```
[info] 	published scala-xml_2.12.0-M1 to https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scala-lang/modules/scala-xml_2.12.0-M1/1.0.6/scala-xml_2.12.0-M1-1.0.6-javadoc.jar.asc
```

because this happened before #108 was merged, artifacts were only published for 2.12.0-M1 and 2.12.0-M5. it isn't immediately obvious to me why 2.11 artifacts weren't published

**Comment by SethTisue** [comment]
over at https://oss.sonatype.org/content/repositories/orgscala-lang-1342/org/scala-lang/modules/ we see artifacts for 2.11, 2.12.0-M1, and 2.12.0-M5. since there are no 2.12.0-RC1 artifacts, since #108 was only merged later, instead of promoting that staging repository to Maven Central, I suggest we let it expire. you can delete the old v1.0.6 tag (keep a copy of the release notes!), merge #108, then push a new tag and Travis should publish again. once that's done, comment here and I'll take a look over on Sonatype to see if we got something we can promote this time.

**Comment by SethTisue** [comment]
> @adriaanm , @SethTisue Can any of you help with
> " Ask Scala compiler to update versions.properties to next release of scala-xml" ?

yes, https://github.com/scala/scala/pull/5410

**Comment by SethTisue** [comment]
@biswanaths I took the liberty of revising the notes at https://github.com/scala/scala-xml/releases/tag/v1.0.6 a bit. in particular, I separated actual user-visible changes from other changes, and put them first. you might want to double-check it

**Comment by biswanaths** [comment]
@SethTisue , release notes look much better.

**Comment by biswanaths** [comment]
@SethTisue , deleting the tag and re-releasing with #108 as suggested by you looks better. We will do as such.

**Comment by biswanaths** [comment]
Done, deleted the tag and released.  @SethTisue  let me know if you need anything else to push to sonatype. Also do we need to push it to maven central ?

**Comment by SethTisue** [comment]
I closed and released the staging repos at oss.sonatype.org just now (it's a manual step in the process that we do through the Sonatype web UI), so the artifacts should show up on Maven Central soon (within the next hour or so)

**Comment by SethTisue** [comment]
1.0.6 is on Maven Central

**Comment by SethTisue** [comment]
> All the items under "Administrative" are TBD -- they're not done yet. I only proposed those things. Sorry if that wasn't clear. Were you planning on doing them?

@ashawley can you double-check the release notes?

**Comment by ashawley** [comment]
The release notes look good to me.  Those are indeed the user-visible changes that you listed first.  Thanks!

**Comment by SethTisue** [comment]
Should we tweet about this from http://twitter.com/scala_lang ?

**Comment by biswanaths** [comment]
@SethTisue , would be great if we tweet. Hope it will drive towards some activity and help us.

**Comment by SethTisue** [comment]
https://twitter.com/scala_lang/status/779062887939575808

**Comment by SethTisue** [comment]
re: driving activity, scala_lang could retweet something you tweeted yourself, as well

**Comment by SethTisue** [comment]
1.0.6 is bundled with Scala 2.12.1, which came out today
